@onerror
{
goto end
}

acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_parameters_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_wr_data_fifo_16.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_wr_data_fifo_8.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_rd_wr_addr_fifo_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_backend_fifos_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_controller_iobs_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_v4_dq_iob.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_v4_dqs_iob.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_data_path_iobs_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_data_tap_inc.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_data_write_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_ddr_controller_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_idelay_ctrl.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_infrastructure.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_infrastructure_iobs_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_iobs_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_pattern_compare4.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_RAM_D_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_rd_data_fifo_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_rd_data_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_tap_ctrl_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_tap_logic_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_user_interface_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_data_path_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top_top_0.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/MIG/mem_interface_top.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/Tester/dat_gen.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/Tester/dat_path.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/Tester/ddr_test_sm.asf"
acom  "$COMMON_HDL/DDR_Ctrl/src/Tester/adr_gen.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/Tester/mctrl_iface.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/Tester/ddr_tester.bde"
acom  "$COMMON_HDL/DDR_Ctrl/src/User-Interface/DDR_Interface_FSM.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/User-Interface/DDR_Interface.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/User-Interface/ddr_block.bde"
acom  "$COMMON_HDL/DDR_Ctrl/src/User-Interface/ddr_top.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/NGC/ddr_wrapper_128d_26a_r1.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/NGC/ddr_NGCwrap_128d_26a_r1.vhd"
label end
