#!/usr/local/bin/perl

if ( (@ARGV != 1)  or ($ARGV[0] eq '-h') or ($ARGV[0] eq 'h') or ($ARGV[0] eq 'help')) 
{
  die <<EOF;

 asciihex2ascii
 This tool reads a file which contains ASCII hex data, decodes it and sends it to
 the console.
 It can be useful to convert a memory dump (generated by XMD for example) to its
 ASCII representation (like the S-Records file that is decoded by a bootloader).
  
 Usage:
 asciihex2ascii asciihex_file.txt
 or
 asciihex2ascii asciihex_file.txt > decoded_ascii.txt

 Patrick Dubois
 prdubois_gmail.com (Drop me an e-mail if you find this tool useful or have comments!)
 Quebec, Canada
 Version 1.0, May 2007
EOF
}

my $source_name = $ARGV[0];


#$buffer = "";


#read(FILE, $buffer, 20, 0);

open(HEXFILE, "<$source_name") or die("Could not open source file.");

foreach my $line (<HEXFILE>) {
   #chomp($line);              # remove the newline from $line.
   
   #Extract each byte from the file
   while ($line =~ /(..)/g) 
   { 
      $byte = $1;
      if (hex($byte) != 13)
      {
         print chr(hex($byte));
      }
   }   
      
}

close(HEXFILE);