acom  "$COMMON_HDL/DDR_Ctrl/src/DDR_tester/dat_gen.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/DDR_tester/dat_path.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/DDR_tester/ddr_test_sm.asf"
acom  "$COMMON_HDL/DDR_Ctrl/src/DDR_tester/adr_gen.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/DDR_tester/mctrl_iface.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/DDR_tester/mem_test.vhd"
acom  "$COMMON_HDL/DDR_Ctrl/src/DDR_tester/ddr_tester.bde"
