#ChipScope Core Inserter Project File Version 3.0
#Tue Jul 08 17:27:06 EDT 2008
Project.device.designInputFile=d\:\\Telops\\Common_HDL\\DDR_Ctrl\\Active-HDL\\Workspace\\workspace\\MIG_tests\\synthesis\\MIG_dataproc_top_merge.ngc
Project.device.designOutputFile=d\:\\Telops\\Common_HDL\\DDR_Ctrl\\Active-HDL\\Workspace\\workspace\\MIG_tests\\synthesis\\MIG_dataproc_top_merge.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=d\:\\Telops\\Common_HDL\\DDR_Ctrl\\Active-HDL\\Workspace\\workspace\\MIG_tests\\synthesis
Project.device.useSRL16=true
Project.filter.dimension=7
Project.filter<0>=
Project.filter<1>=MEM*
Project.filter<2>=mem*
Project.filter<3>=comp*
Project.filter<4>=init*
Project.filter<5>=done*
Project.filter<6>=auto*
Project.icon.boundaryScanChain=0
Project.icon.disableBUFGInsertion=false
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=CLK_DDR0
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=CORE_INITDONE
Project.unit<0>.dataChannel<100>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<2>
Project.unit<0>.dataChannel<101>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<3>
Project.unit<0>.dataChannel<102>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 CHAN_DONE
Project.unit<0>.dataChannel<103>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DLYINC_GLOBAL_FLAG
Project.unit<0>.dataChannel<104>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<0>
Project.unit<0>.dataChannel<105>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<1>
Project.unit<0>.dataChannel<106>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<2>
Project.unit<0>.dataChannel<107>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<3>
Project.unit<0>.dataChannel<108>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 CALIB_DONE
Project.unit<0>.dataChannel<109>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 COMPARE_BIT
Project.unit<0>.dataChannel<10>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<9>
Project.unit<0>.dataChannel<110>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 CTRL_CALIB_START
Project.unit<0>.dataChannel<111>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<0>
Project.unit<0>.dataChannel<112>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<1>
Project.unit<0>.dataChannel<113>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<2>
Project.unit<0>.dataChannel<114>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<3>
Project.unit<0>.dataChannel<115>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<0>
Project.unit<0>.dataChannel<116>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<1>
Project.unit<0>.dataChannel<117>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<2>
Project.unit<0>.dataChannel<118>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<3>
Project.unit<0>.dataChannel<119>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYRST<0>
Project.unit<0>.dataChannel<11>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<10>
Project.unit<0>.dataChannel<120>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DLYCE
Project.unit<0>.dataChannel<121>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DLYINC
Project.unit<0>.dataChannel<122>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DQ_DATA
Project.unit<0>.dataChannel<123>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 BIT_BOUNDARY_CHECK
Project.unit<0>.dataChannel<12>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<11>
Project.unit<0>.dataChannel<13>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<12>
Project.unit<0>.dataChannel<14>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<13>
Project.unit<0>.dataChannel<15>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<14>
Project.unit<0>.dataChannel<16>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<15>
Project.unit<0>.dataChannel<17>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<16>
Project.unit<0>.dataChannel<18>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<17>
Project.unit<0>.dataChannel<19>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<0>
Project.unit<0>.dataChannel<1>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<0>
Project.unit<0>.dataChannel<20>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<1>
Project.unit<0>.dataChannel<21>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<2>
Project.unit<0>.dataChannel<22>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<3>
Project.unit<0>.dataChannel<23>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<4>
Project.unit<0>.dataChannel<24>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<5>
Project.unit<0>.dataChannel<25>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<6>
Project.unit<0>.dataChannel<26>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<7>
Project.unit<0>.dataChannel<27>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<8>
Project.unit<0>.dataChannel<28>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<9>
Project.unit<0>.dataChannel<29>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<10>
Project.unit<0>.dataChannel<2>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<1>
Project.unit<0>.dataChannel<30>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<11>
Project.unit<0>.dataChannel<31>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<12>
Project.unit<0>.dataChannel<32>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<13>
Project.unit<0>.dataChannel<33>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<14>
Project.unit<0>.dataChannel<34>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<15>
Project.unit<0>.dataChannel<35>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<16>
Project.unit<0>.dataChannel<36>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<17>
Project.unit<0>.dataChannel<37>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 data_tap_inc_done
Project.unit<0>.dataChannel<38>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 SEL_DONE
Project.unit<0>.dataChannel<39>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<0>
Project.unit<0>.dataChannel<3>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<2>
Project.unit<0>.dataChannel<40>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<1>
Project.unit<0>.dataChannel<41>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<2>
Project.unit<0>.dataChannel<42>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<3>
Project.unit<0>.dataChannel<43>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<4>
Project.unit<0>.dataChannel<44>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 auto_ref
Project.unit<0>.dataChannel<45>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_memory
Project.unit<0>.dataChannel<46>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 done_200us
Project.unit<0>.dataChannel<47>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<0>
Project.unit<0>.dataChannel<48>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<1>
Project.unit<0>.dataChannel<49>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<2>
Project.unit<0>.dataChannel<4>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<3>
Project.unit<0>.dataChannel<50>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<3>
Project.unit<0>.dataChannel<51>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 comp_done
Project.unit<0>.dataChannel<52>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 comp_done_r
Project.unit<0>.dataChannel<53>=DDR MEM_INITDONE
Project.unit<0>.dataChannel<54>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 CTRL_DUMMYREAD_START
Project.unit<0>.dataChannel<55>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 calib_start
Project.unit<0>.dataChannel<56>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 BIT_BOUNDARY_CHECK
Project.unit<0>.dataChannel<57>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<0>
Project.unit<0>.dataChannel<58>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<1>
Project.unit<0>.dataChannel<59>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<2>
Project.unit<0>.dataChannel<5>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<4>
Project.unit<0>.dataChannel<60>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<3>
Project.unit<0>.dataChannel<61>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_inc<0>
Project.unit<0>.dataChannel<62>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_inc<1>
Project.unit<0>.dataChannel<63>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 bit_boundary_aligned
Project.unit<0>.dataChannel<64>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count_inc
Project.unit<0>.dataChannel<65>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count_rst
Project.unit<0>.dataChannel<66>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 inc_flag
Project.unit<0>.dataChannel<67>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DLYCE
Project.unit<0>.dataChannel<68>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DLYINC
Project.unit<0>.dataChannel<69>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<0>
Project.unit<0>.dataChannel<6>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<5>
Project.unit<0>.dataChannel<70>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<1>
Project.unit<0>.dataChannel<71>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<2>
Project.unit<0>.dataChannel<72>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<3>
Project.unit<0>.dataChannel<73>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<4>
Project.unit<0>.dataChannel<74>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<5>
Project.unit<0>.dataChannel<75>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DQ_DATA
Project.unit<0>.dataChannel<76>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DQ_DATA_R
Project.unit<0>.dataChannel<77>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<0>
Project.unit<0>.dataChannel<78>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<1>
Project.unit<0>.dataChannel<79>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<2>
Project.unit<0>.dataChannel<7>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<6>
Project.unit<0>.dataChannel<80>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<3>
Project.unit<0>.dataChannel<81>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<4>
Project.unit<0>.dataChannel<82>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<5>
Project.unit<0>.dataChannel<83>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 compare
Project.unit<0>.dataChannel<84>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd1
Project.unit<0>.dataChannel<85>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd2
Project.unit<0>.dataChannel<86>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd3
Project.unit<0>.dataChannel<87>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd4
Project.unit<0>.dataChannel<88>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<0>
Project.unit<0>.dataChannel<89>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<1>
Project.unit<0>.dataChannel<8>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<7>
Project.unit<0>.dataChannel<90>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<2>
Project.unit<0>.dataChannel<91>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<3>
Project.unit<0>.dataChannel<92>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<4>
Project.unit<0>.dataChannel<93>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<5>
Project.unit<0>.dataChannel<94>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_inc
Project.unit<0>.dataChannel<95>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 RDY_STATUS
Project.unit<0>.dataChannel<96>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 COMPARE_BIT
Project.unit<0>.dataChannel<97>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 reset_int
Project.unit<0>.dataChannel<98>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<0>
Project.unit<0>.dataChannel<99>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<1>
Project.unit<0>.dataChannel<9>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<8>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=255
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=CORE_INITDONE
Project.unit<0>.triggerChannel<0><100>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<2>
Project.unit<0>.triggerChannel<0><101>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<3>
Project.unit<0>.triggerChannel<0><102>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 CHAN_DONE
Project.unit<0>.triggerChannel<0><103>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DLYINC_GLOBAL_FLAG
Project.unit<0>.triggerChannel<0><104>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<0>
Project.unit<0>.triggerChannel<0><105>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<1>
Project.unit<0>.triggerChannel<0><106>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<2>
Project.unit<0>.triggerChannel<0><107>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 calibration_dq_r<3>
Project.unit<0>.triggerChannel<0><108>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 CALIB_DONE
Project.unit<0>.triggerChannel<0><109>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 COMPARE_BIT
Project.unit<0>.triggerChannel<0><10>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<9>
Project.unit<0>.triggerChannel<0><110>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 CTRL_CALIB_START
Project.unit<0>.triggerChannel<0><111>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<0>
Project.unit<0>.triggerChannel<0><112>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<1>
Project.unit<0>.triggerChannel<0><113>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<2>
Project.unit<0>.triggerChannel<0><114>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYCE<3>
Project.unit<0>.triggerChannel<0><115>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<0>
Project.unit<0>.triggerChannel<0><116>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<1>
Project.unit<0>.triggerChannel<0><117>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<2>
Project.unit<0>.triggerChannel<0><118>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYINC<3>
Project.unit<0>.triggerChannel<0><119>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DATA_DLYRST<0>
Project.unit<0>.triggerChannel<0><11>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<10>
Project.unit<0>.triggerChannel<0><120>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DLYCE
Project.unit<0>.triggerChannel<0><121>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DLYINC
Project.unit<0>.triggerChannel<0><122>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 DQ_DATA
Project.unit<0>.triggerChannel<0><123>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 BIT_BOUNDARY_CHECK
Project.unit<0>.triggerChannel<0><124>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<0>
Project.unit<0>.triggerChannel<0><125>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<1>
Project.unit<0>.triggerChannel<0><126>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<2>
Project.unit<0>.triggerChannel<0><127>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<3>
Project.unit<0>.triggerChannel<0><128>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<4>
Project.unit<0>.triggerChannel<0><129>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<5>
Project.unit<0>.triggerChannel<0><12>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<11>
Project.unit<0>.triggerChannel<0><130>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<6>
Project.unit<0>.triggerChannel<0><131>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<7>
Project.unit<0>.triggerChannel<0><132>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<8>
Project.unit<0>.triggerChannel<0><133>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<9>
Project.unit<0>.triggerChannel<0><134>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<10>
Project.unit<0>.triggerChannel<0><135>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<11>
Project.unit<0>.triggerChannel<0><136>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_address_init_r<12>
Project.unit<0>.triggerChannel<0><137>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_ba_r1<0>
Project.unit<0>.triggerChannel<0><138>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_ba_r1<1>
Project.unit<0>.triggerChannel<0><139>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_cas_r2
Project.unit<0>.triggerChannel<0><13>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<12>
Project.unit<0>.triggerChannel<0><140>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_ras_r2
Project.unit<0>.triggerChannel<0><141>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_we_r2
Project.unit<0>.triggerChannel<0><142>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_cs_r1<0>
Project.unit<0>.triggerChannel<0><143>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ddr_cs_r1<1>
Project.unit<0>.triggerChannel<0><144>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 ctrl_Wdf_RdEn
Project.unit<0>.triggerChannel<0><145>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<0>
Project.unit<0>.triggerChannel<0><146>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<1>
Project.unit<0>.triggerChannel<0><147>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<2>
Project.unit<0>.triggerChannel<0><148>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<3>
Project.unit<0>.triggerChannel<0><149>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<4>
Project.unit<0>.triggerChannel<0><14>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<13>
Project.unit<0>.triggerChannel<0><150>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<5>
Project.unit<0>.triggerChannel<0><151>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<6>
Project.unit<0>.triggerChannel<0><152>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<7>
Project.unit<0>.triggerChannel<0><153>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<8>
Project.unit<0>.triggerChannel<0><154>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<9>
Project.unit<0>.triggerChannel<0><155>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<10>
Project.unit<0>.triggerChannel<0><156>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<11>
Project.unit<0>.triggerChannel<0><157>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<12>
Project.unit<0>.triggerChannel<0><158>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<13>
Project.unit<0>.triggerChannel<0><159>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<14>
Project.unit<0>.triggerChannel<0><15>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<14>
Project.unit<0>.triggerChannel<0><160>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<15>
Project.unit<0>.triggerChannel<0><161>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<72>
Project.unit<0>.triggerChannel<0><162>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<73>
Project.unit<0>.triggerChannel<0><163>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<74>
Project.unit<0>.triggerChannel<0><164>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<75>
Project.unit<0>.triggerChannel<0><165>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<76>
Project.unit<0>.triggerChannel<0><166>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<77>
Project.unit<0>.triggerChannel<0><167>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<78>
Project.unit<0>.triggerChannel<0><168>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<79>
Project.unit<0>.triggerChannel<0><169>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<80>
Project.unit<0>.triggerChannel<0><16>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<15>
Project.unit<0>.triggerChannel<0><170>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<81>
Project.unit<0>.triggerChannel<0><171>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<82>
Project.unit<0>.triggerChannel<0><172>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<83>
Project.unit<0>.triggerChannel<0><173>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<84>
Project.unit<0>.triggerChannel<0><174>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<85>
Project.unit<0>.triggerChannel<0><175>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<86>
Project.unit<0>.triggerChannel<0><176>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 Wdf_data<87>
Project.unit<0>.triggerChannel<0><177>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 rst
Project.unit<0>.triggerChannel<0><178>=DDR ddr DDR_controller mig_core top_00 user_interface_00 backend_fifos_00 rst_r1
Project.unit<0>.triggerChannel<0><179>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 burst_cnt<3>1
Project.unit<0>.triggerChannel<0><17>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<16>
Project.unit<0>.triggerChannel<0><180>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 wdf_rden_r
Project.unit<0>.triggerChannel<0><181>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 wdf_rden_r2
Project.unit<0>.triggerChannel<0><182>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 wdf_rden_r3
Project.unit<0>.triggerChannel<0><183>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 wdf_rden_r4
Project.unit<0>.triggerChannel<0><184>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 ctrl_dummy_wr_sel
Project.unit<0>.triggerChannel<0><185>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<0>
Project.unit<0>.triggerChannel<0><186>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<1>
Project.unit<0>.triggerChannel<0><187>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<2>
Project.unit<0>.triggerChannel<0><188>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<3>
Project.unit<0>.triggerChannel<0><189>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count_cp<0>
Project.unit<0>.triggerChannel<0><18>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<17>
Project.unit<0>.triggerChannel<0><190>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count_cp<1>
Project.unit<0>.triggerChannel<0><191>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count_cp<2>
Project.unit<0>.triggerChannel<0><192>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count_cp<3>
Project.unit<0>.triggerChannel<0><193>=
Project.unit<0>.triggerChannel<0><194>=
Project.unit<0>.triggerChannel<0><195>=
Project.unit<0>.triggerChannel<0><196>=
Project.unit<0>.triggerChannel<0><197>=
Project.unit<0>.triggerChannel<0><198>=
Project.unit<0>.triggerChannel<0><199>=
Project.unit<0>.triggerChannel<0><19>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<0>
Project.unit<0>.triggerChannel<0><1>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<0>
Project.unit<0>.triggerChannel<0><200>=
Project.unit<0>.triggerChannel<0><201>=
Project.unit<0>.triggerChannel<0><202>=
Project.unit<0>.triggerChannel<0><203>=
Project.unit<0>.triggerChannel<0><204>=
Project.unit<0>.triggerChannel<0><205>=
Project.unit<0>.triggerChannel<0><206>=
Project.unit<0>.triggerChannel<0><207>=
Project.unit<0>.triggerChannel<0><208>=
Project.unit<0>.triggerChannel<0><209>=
Project.unit<0>.triggerChannel<0><20>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<1>
Project.unit<0>.triggerChannel<0><210>=
Project.unit<0>.triggerChannel<0><211>=
Project.unit<0>.triggerChannel<0><212>=
Project.unit<0>.triggerChannel<0><213>=
Project.unit<0>.triggerChannel<0><214>=
Project.unit<0>.triggerChannel<0><215>=
Project.unit<0>.triggerChannel<0><216>=
Project.unit<0>.triggerChannel<0><217>=
Project.unit<0>.triggerChannel<0><218>=
Project.unit<0>.triggerChannel<0><219>=
Project.unit<0>.triggerChannel<0><21>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<2>
Project.unit<0>.triggerChannel<0><220>=
Project.unit<0>.triggerChannel<0><221>=
Project.unit<0>.triggerChannel<0><222>=
Project.unit<0>.triggerChannel<0><223>=
Project.unit<0>.triggerChannel<0><224>=
Project.unit<0>.triggerChannel<0><225>=
Project.unit<0>.triggerChannel<0><226>=
Project.unit<0>.triggerChannel<0><227>=
Project.unit<0>.triggerChannel<0><228>=
Project.unit<0>.triggerChannel<0><229>=
Project.unit<0>.triggerChannel<0><22>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<3>
Project.unit<0>.triggerChannel<0><230>=
Project.unit<0>.triggerChannel<0><231>=
Project.unit<0>.triggerChannel<0><232>=
Project.unit<0>.triggerChannel<0><233>=
Project.unit<0>.triggerChannel<0><234>=
Project.unit<0>.triggerChannel<0><235>=
Project.unit<0>.triggerChannel<0><236>=
Project.unit<0>.triggerChannel<0><237>=
Project.unit<0>.triggerChannel<0><238>=
Project.unit<0>.triggerChannel<0><239>=
Project.unit<0>.triggerChannel<0><23>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<4>
Project.unit<0>.triggerChannel<0><240>=
Project.unit<0>.triggerChannel<0><241>=
Project.unit<0>.triggerChannel<0><242>=
Project.unit<0>.triggerChannel<0><243>=
Project.unit<0>.triggerChannel<0><244>=
Project.unit<0>.triggerChannel<0><245>=
Project.unit<0>.triggerChannel<0><246>=
Project.unit<0>.triggerChannel<0><247>=
Project.unit<0>.triggerChannel<0><248>=
Project.unit<0>.triggerChannel<0><249>=
Project.unit<0>.triggerChannel<0><24>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<5>
Project.unit<0>.triggerChannel<0><250>=
Project.unit<0>.triggerChannel<0><251>=
Project.unit<0>.triggerChannel<0><252>=
Project.unit<0>.triggerChannel<0><253>=
Project.unit<0>.triggerChannel<0><254>=
Project.unit<0>.triggerChannel<0><25>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<6>
Project.unit<0>.triggerChannel<0><26>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<7>
Project.unit<0>.triggerChannel<0><27>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<8>
Project.unit<0>.triggerChannel<0><28>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<9>
Project.unit<0>.triggerChannel<0><29>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<10>
Project.unit<0>.triggerChannel<0><2>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<1>
Project.unit<0>.triggerChannel<0><30>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<11>
Project.unit<0>.triggerChannel<0><31>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<12>
Project.unit<0>.triggerChannel<0><32>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<13>
Project.unit<0>.triggerChannel<0><33>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<14>
Project.unit<0>.triggerChannel<0><34>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<15>
Project.unit<0>.triggerChannel<0><35>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<16>
Project.unit<0>.triggerChannel<0><36>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 chan_done_dqs<17>
Project.unit<0>.triggerChannel<0><37>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 data_tap_inc_done
Project.unit<0>.triggerChannel<0><38>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 SEL_DONE
Project.unit<0>.triggerChannel<0><39>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<0>
Project.unit<0>.triggerChannel<0><3>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<2>
Project.unit<0>.triggerChannel<0><40>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<1>
Project.unit<0>.triggerChannel<0><41>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<2>
Project.unit<0>.triggerChannel<0><42>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<3>
Project.unit<0>.triggerChannel<0><43>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 count5<4>
Project.unit<0>.triggerChannel<0><44>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 auto_ref
Project.unit<0>.triggerChannel<0><45>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_memory
Project.unit<0>.triggerChannel<0><46>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 done_200us
Project.unit<0>.triggerChannel<0><47>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<0>
Project.unit<0>.triggerChannel<0><48>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<1>
Project.unit<0>.triggerChannel<0><49>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<2>
Project.unit<0>.triggerChannel<0><4>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<3>
Project.unit<0>.triggerChannel<0><50>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 init_count<3>
Project.unit<0>.triggerChannel<0><51>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 comp_done
Project.unit<0>.triggerChannel<0><52>=DDR ddr DDR_controller mig_core top_00 ddr_controller_00 comp_done_r
Project.unit<0>.triggerChannel<0><53>=DDR MEM_INITDONE
Project.unit<0>.triggerChannel<0><54>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 CTRL_DUMMYREAD_START
Project.unit<0>.triggerChannel<0><55>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 calib_start
Project.unit<0>.triggerChannel<0><56>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 BIT_BOUNDARY_CHECK
Project.unit<0>.triggerChannel<0><57>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<0>
Project.unit<0>.triggerChannel<0><58>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<1>
Project.unit<0>.triggerChannel<0><59>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<2>
Project.unit<0>.triggerChannel<0><5>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<4>
Project.unit<0>.triggerChannel<0><60>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 check_boundary_count<3>
Project.unit<0>.triggerChannel<0><61>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_inc<0>
Project.unit<0>.triggerChannel<0><62>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_inc<1>
Project.unit<0>.triggerChannel<0><63>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 bit_boundary_aligned
Project.unit<0>.triggerChannel<0><64>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count_inc
Project.unit<0>.triggerChannel<0><65>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count_rst
Project.unit<0>.triggerChannel<0><66>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 inc_flag
Project.unit<0>.triggerChannel<0><67>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DLYCE
Project.unit<0>.triggerChannel<0><68>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DLYINC
Project.unit<0>.triggerChannel<0><69>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<0>
Project.unit<0>.triggerChannel<0><6>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<5>
Project.unit<0>.triggerChannel<0><70>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<1>
Project.unit<0>.triggerChannel<0><71>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<2>
Project.unit<0>.triggerChannel<0><72>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<3>
Project.unit<0>.triggerChannel<0><73>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<4>
Project.unit<0>.triggerChannel<0><74>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 tap_count<5>
Project.unit<0>.triggerChannel<0><75>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DQ_DATA
Project.unit<0>.triggerChannel<0><76>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 DQ_DATA_R
Project.unit<0>.triggerChannel<0><77>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<0>
Project.unit<0>.triggerChannel<0><78>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<1>
Project.unit<0>.triggerChannel<0><79>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<2>
Project.unit<0>.triggerChannel<0><7>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<6>
Project.unit<0>.triggerChannel<0><80>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<3>
Project.unit<0>.triggerChannel<0><81>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<4>
Project.unit<0>.triggerChannel<0><82>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 dec_count<5>
Project.unit<0>.triggerChannel<0><83>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 compare
Project.unit<0>.triggerChannel<0><84>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd1
Project.unit<0>.triggerChannel<0><85>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd2
Project.unit<0>.triggerChannel<0><86>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd3
Project.unit<0>.triggerChannel<0><87>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 Current_State_FFd4
Project.unit<0>.triggerChannel<0><88>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<0>
Project.unit<0>.triggerChannel<0><89>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<1>
Project.unit<0>.triggerChannel<0><8>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<7>
Project.unit<0>.triggerChannel<0><90>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<2>
Project.unit<0>.triggerChannel<0><91>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<3>
Project.unit<0>.triggerChannel<0><92>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<4>
Project.unit<0>.triggerChannel<0><93>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_cnt<5>
Project.unit<0>.triggerChannel<0><94>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 init_tap_inc
Project.unit<0>.triggerChannel<0><95>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 RDY_STATUS
Project.unit<0>.triggerChannel<0><96>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 COMPARE_BIT
Project.unit<0>.triggerChannel<0><97>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].tap_ctrl_0 reset_int
Project.unit<0>.triggerChannel<0><98>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<0>
Project.unit<0>.triggerChannel<0><99>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 tap_ctrl_gen[0].data_tap_inc_0 chan_sel_int<1>
Project.unit<0>.triggerChannel<0><9>=DDR ddr DDR_controller mig_core top_00 data_path_00 tap_logic_00 calib_done_dqs<8>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=2
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<0><1>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<0><1>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=193
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
