#ChipScope Core Inserter Project File Version 3.0
#Mon May 10 09:35:20 EDT 2010
Project.device.designInputFile=D\:\\Telops\\Common_HDL\\Telops_Memory_Interface\\TMI_BRAM_test_proj\\ise\\plb2tmi_tst_Top_cs.ngc
Project.device.designOutputFile=D\:\\Telops\\Common_HDL\\Telops_Memory_Interface\\TMI_BRAM_test_proj\\ise\\plb2tmi_tst_Top_cs.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\Telops\\Common_HDL\\Telops_Memory_Interface\\TMI_BRAM_test_proj\\ise\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*clk*
Project.filter<10>=*TMI_ERROR*
Project.filter<11>=*TMI_ERROR *
Project.filter<12>=*TMI_WR_DATA*
Project.filter<13>=*TMI_RD_DATA*
Project.filter<14>=*busy*
Project.filter<15>=*TMI_BUSY *
Project.filter<16>=*DVaL*
Project.filter<17>=*DAVL*
Project.filter<18>=*ADD*
Project.filter<1>=
Project.filter<2>=*flag*
Project.filter<3>=flag*
Project.filter<4>=code*
Project.filter<5>=*_OUT_*
Project.filter<6>=*_IN_*
Project.filter<7>=**
Project.filter<8>=*fed*
Project.filter<9>=*falling*
Project.icon.boundaryScanChain=1
Project.icon.disableBUFGInsertion=false
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=mem160Mhz_clk_s
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=tmi_arst_s
Project.unit<0>.dataChannel<100>=u0_tmi_afifo TMI_OUT_RD_DATA<5>
Project.unit<0>.dataChannel<101>=u0_tmi_afifo TMI_OUT_RD_DATA<6>
Project.unit<0>.dataChannel<102>=u0_tmi_afifo TMI_OUT_RD_DATA<7>
Project.unit<0>.dataChannel<103>=u0_tmi_afifo TMI_OUT_RD_DATA<8>
Project.unit<0>.dataChannel<104>=u0_tmi_afifo TMI_OUT_RD_DATA<9>
Project.unit<0>.dataChannel<105>=u0_tmi_afifo TMI_OUT_RD_DATA<10>
Project.unit<0>.dataChannel<106>=u0_tmi_afifo TMI_OUT_RD_DATA<11>
Project.unit<0>.dataChannel<107>=u0_tmi_afifo TMI_OUT_RD_DATA<12>
Project.unit<0>.dataChannel<108>=u0_tmi_afifo TMI_OUT_RD_DATA<13>
Project.unit<0>.dataChannel<109>=u0_tmi_afifo TMI_OUT_RD_DATA<14>
Project.unit<0>.dataChannel<10>=u0_tmi_afifo TMI_IN_ADD<0>
Project.unit<0>.dataChannel<110>=u0_tmi_afifo TMI_OUT_RD_DATA<15>
Project.unit<0>.dataChannel<111>=u0_tmi_afifo TMI_OUT_RD_DATA<16>
Project.unit<0>.dataChannel<112>=u0_tmi_afifo TMI_OUT_RD_DATA<17>
Project.unit<0>.dataChannel<113>=u0_tmi_afifo TMI_OUT_RD_DATA<18>
Project.unit<0>.dataChannel<114>=u0_tmi_afifo TMI_OUT_RD_DATA<19>
Project.unit<0>.dataChannel<115>=u0_tmi_afifo TMI_OUT_RD_DATA<20>
Project.unit<0>.dataChannel<116>=u0_tmi_afifo TMI_OUT_RD_DATA<21>
Project.unit<0>.dataChannel<117>=u0_tmi_afifo TMI_OUT_RD_DATA<22>
Project.unit<0>.dataChannel<118>=u0_tmi_afifo TMI_OUT_RD_DATA<23>
Project.unit<0>.dataChannel<119>=u0_tmi_afifo TMI_OUT_RD_DATA<24>
Project.unit<0>.dataChannel<11>=u0_tmi_afifo TMI_IN_ADD<1>
Project.unit<0>.dataChannel<120>=u0_tmi_afifo TMI_OUT_RD_DATA<25>
Project.unit<0>.dataChannel<121>=u0_tmi_afifo TMI_OUT_RD_DATA<26>
Project.unit<0>.dataChannel<122>=u0_tmi_afifo TMI_OUT_RD_DATA<27>
Project.unit<0>.dataChannel<123>=u0_tmi_afifo TMI_OUT_RD_DATA<28>
Project.unit<0>.dataChannel<124>=u0_tmi_afifo TMI_OUT_RD_DATA<29>
Project.unit<0>.dataChannel<125>=u0_tmi_afifo TMI_OUT_RD_DATA<30>
Project.unit<0>.dataChannel<126>=u0_tmi_afifo TMI_OUT_RD_DATA<31>
Project.unit<0>.dataChannel<127>=u0_tmi_afifo TMI_OUT_RD_DVAL
Project.unit<0>.dataChannel<128>=u0_tmi_afifo TMI_OUT_WR_DATA<0>
Project.unit<0>.dataChannel<129>=u0_tmi_afifo TMI_OUT_WR_DATA<1>
Project.unit<0>.dataChannel<12>=u0_tmi_afifo TMI_IN_ADD<2>
Project.unit<0>.dataChannel<130>=u0_tmi_afifo TMI_OUT_WR_DATA<2>
Project.unit<0>.dataChannel<131>=u0_tmi_afifo TMI_OUT_WR_DATA<3>
Project.unit<0>.dataChannel<132>=u0_tmi_afifo TMI_OUT_WR_DATA<4>
Project.unit<0>.dataChannel<133>=u0_tmi_afifo TMI_OUT_WR_DATA<5>
Project.unit<0>.dataChannel<134>=u0_tmi_afifo TMI_OUT_WR_DATA<6>
Project.unit<0>.dataChannel<135>=u0_tmi_afifo TMI_OUT_WR_DATA<7>
Project.unit<0>.dataChannel<136>=u0_tmi_afifo TMI_OUT_WR_DATA<8>
Project.unit<0>.dataChannel<137>=u0_tmi_afifo TMI_OUT_WR_DATA<9>
Project.unit<0>.dataChannel<138>=u0_tmi_afifo TMI_OUT_WR_DATA<10>
Project.unit<0>.dataChannel<139>=u0_tmi_afifo TMI_OUT_WR_DATA<11>
Project.unit<0>.dataChannel<13>=u0_tmi_afifo TMI_IN_ADD<3>
Project.unit<0>.dataChannel<140>=u0_tmi_afifo TMI_OUT_WR_DATA<12>
Project.unit<0>.dataChannel<141>=u0_tmi_afifo TMI_OUT_WR_DATA<13>
Project.unit<0>.dataChannel<142>=u0_tmi_afifo TMI_OUT_WR_DATA<14>
Project.unit<0>.dataChannel<143>=u0_tmi_afifo TMI_OUT_WR_DATA<15>
Project.unit<0>.dataChannel<144>=u0_tmi_afifo TMI_OUT_WR_DATA<16>
Project.unit<0>.dataChannel<145>=u0_tmi_afifo TMI_OUT_WR_DATA<17>
Project.unit<0>.dataChannel<146>=u0_tmi_afifo TMI_OUT_WR_DATA<18>
Project.unit<0>.dataChannel<147>=u0_tmi_afifo TMI_OUT_WR_DATA<19>
Project.unit<0>.dataChannel<148>=u0_tmi_afifo TMI_OUT_WR_DATA<20>
Project.unit<0>.dataChannel<149>=u0_tmi_afifo TMI_OUT_WR_DATA<21>
Project.unit<0>.dataChannel<14>=u0_tmi_afifo TMI_IN_ADD<4>
Project.unit<0>.dataChannel<150>=u0_tmi_afifo TMI_OUT_WR_DATA<22>
Project.unit<0>.dataChannel<151>=u0_tmi_afifo TMI_OUT_WR_DATA<23>
Project.unit<0>.dataChannel<152>=u0_tmi_afifo TMI_OUT_WR_DATA<24>
Project.unit<0>.dataChannel<153>=u0_tmi_afifo TMI_OUT_WR_DATA<25>
Project.unit<0>.dataChannel<154>=u0_tmi_afifo TMI_OUT_WR_DATA<26>
Project.unit<0>.dataChannel<155>=u0_tmi_afifo TMI_OUT_WR_DATA<27>
Project.unit<0>.dataChannel<156>=u0_tmi_afifo TMI_OUT_WR_DATA<28>
Project.unit<0>.dataChannel<157>=u0_tmi_afifo TMI_OUT_WR_DATA<29>
Project.unit<0>.dataChannel<158>=u0_tmi_afifo TMI_OUT_WR_DATA<30>
Project.unit<0>.dataChannel<159>=u0_tmi_afifo TMI_OUT_WR_DATA<31>
Project.unit<0>.dataChannel<15>=u0_tmi_afifo TMI_IN_ADD<5>
Project.unit<0>.dataChannel<160>=err_flag_s<0>
Project.unit<0>.dataChannel<161>=err_flag_s<1>
Project.unit<0>.dataChannel<16>=u0_tmi_afifo TMI_IN_ADD<6>
Project.unit<0>.dataChannel<17>=u0_tmi_afifo TMI_IN_ADD<7>
Project.unit<0>.dataChannel<18>=u0_tmi_afifo TMI_IN_RD_DATA<0>
Project.unit<0>.dataChannel<19>=u0_tmi_afifo TMI_IN_RD_DATA<1>
Project.unit<0>.dataChannel<1>=tmi_arst_Fedge
Project.unit<0>.dataChannel<20>=u0_tmi_afifo TMI_IN_RD_DATA<2>
Project.unit<0>.dataChannel<21>=u0_tmi_afifo TMI_IN_RD_DATA<3>
Project.unit<0>.dataChannel<22>=u0_tmi_afifo TMI_IN_RD_DATA<4>
Project.unit<0>.dataChannel<23>=u0_tmi_afifo TMI_IN_RD_DATA<5>
Project.unit<0>.dataChannel<24>=u0_tmi_afifo TMI_IN_RD_DATA<6>
Project.unit<0>.dataChannel<25>=u0_tmi_afifo TMI_IN_RD_DATA<7>
Project.unit<0>.dataChannel<26>=u0_tmi_afifo TMI_IN_RD_DATA<8>
Project.unit<0>.dataChannel<27>=u0_tmi_afifo TMI_IN_RD_DATA<9>
Project.unit<0>.dataChannel<28>=u0_tmi_afifo TMI_IN_RD_DATA<10>
Project.unit<0>.dataChannel<29>=u0_tmi_afifo TMI_IN_RD_DATA<11>
Project.unit<0>.dataChannel<2>=start_test_s
Project.unit<0>.dataChannel<30>=u0_tmi_afifo TMI_IN_RD_DATA<12>
Project.unit<0>.dataChannel<31>=u0_tmi_afifo TMI_IN_RD_DATA<13>
Project.unit<0>.dataChannel<32>=u0_tmi_afifo TMI_IN_RD_DATA<14>
Project.unit<0>.dataChannel<33>=u0_tmi_afifo TMI_IN_RD_DATA<15>
Project.unit<0>.dataChannel<34>=u0_tmi_afifo TMI_IN_RD_DATA<16>
Project.unit<0>.dataChannel<35>=u0_tmi_afifo TMI_IN_RD_DATA<17>
Project.unit<0>.dataChannel<36>=u0_tmi_afifo TMI_IN_RD_DATA<18>
Project.unit<0>.dataChannel<37>=u0_tmi_afifo TMI_IN_RD_DATA<19>
Project.unit<0>.dataChannel<38>=u0_tmi_afifo TMI_IN_RD_DATA<20>
Project.unit<0>.dataChannel<39>=u0_tmi_afifo TMI_IN_RD_DATA<21>
Project.unit<0>.dataChannel<3>=u0_TMI_memtest TEST_DONE
Project.unit<0>.dataChannel<40>=u0_tmi_afifo TMI_IN_RD_DATA<22>
Project.unit<0>.dataChannel<41>=u0_tmi_afifo TMI_IN_RD_DATA<23>
Project.unit<0>.dataChannel<42>=u0_tmi_afifo TMI_IN_RD_DATA<24>
Project.unit<0>.dataChannel<43>=u0_tmi_afifo TMI_IN_RD_DATA<25>
Project.unit<0>.dataChannel<44>=u0_tmi_afifo TMI_IN_RD_DATA<26>
Project.unit<0>.dataChannel<45>=u0_tmi_afifo TMI_IN_RD_DATA<27>
Project.unit<0>.dataChannel<46>=u0_tmi_afifo TMI_IN_RD_DATA<28>
Project.unit<0>.dataChannel<47>=u0_tmi_afifo TMI_IN_RD_DATA<29>
Project.unit<0>.dataChannel<48>=u0_tmi_afifo TMI_IN_RD_DATA<30>
Project.unit<0>.dataChannel<49>=u0_tmi_afifo TMI_IN_RD_DATA<31>
Project.unit<0>.dataChannel<4>=u0_TMI_memtest TEST_PASS
Project.unit<0>.dataChannel<50>=u0_tmi_afifo TMI_IN_RD_DVAL
Project.unit<0>.dataChannel<51>=u0_tmi_afifo TMI_IN_WR_DATA<0>
Project.unit<0>.dataChannel<52>=u0_tmi_afifo TMI_IN_WR_DATA<1>
Project.unit<0>.dataChannel<53>=u0_tmi_afifo TMI_IN_WR_DATA<2>
Project.unit<0>.dataChannel<54>=u0_tmi_afifo TMI_IN_WR_DATA<3>
Project.unit<0>.dataChannel<55>=u0_tmi_afifo TMI_IN_WR_DATA<4>
Project.unit<0>.dataChannel<56>=u0_tmi_afifo TMI_IN_WR_DATA<5>
Project.unit<0>.dataChannel<57>=u0_tmi_afifo TMI_IN_WR_DATA<6>
Project.unit<0>.dataChannel<58>=u0_tmi_afifo TMI_IN_WR_DATA<7>
Project.unit<0>.dataChannel<59>=u0_tmi_afifo TMI_IN_WR_DATA<8>
Project.unit<0>.dataChannel<5>=u0_tmi_afifo TMI_IN_DVAL
Project.unit<0>.dataChannel<60>=u0_tmi_afifo TMI_IN_WR_DATA<9>
Project.unit<0>.dataChannel<61>=u0_tmi_afifo TMI_IN_WR_DATA<10>
Project.unit<0>.dataChannel<62>=u0_tmi_afifo TMI_IN_WR_DATA<11>
Project.unit<0>.dataChannel<63>=u0_tmi_afifo TMI_IN_WR_DATA<12>
Project.unit<0>.dataChannel<64>=u0_tmi_afifo TMI_IN_WR_DATA<13>
Project.unit<0>.dataChannel<65>=u0_tmi_afifo TMI_IN_WR_DATA<14>
Project.unit<0>.dataChannel<66>=u0_tmi_afifo TMI_IN_WR_DATA<15>
Project.unit<0>.dataChannel<67>=u0_tmi_afifo TMI_IN_WR_DATA<16>
Project.unit<0>.dataChannel<68>=u0_tmi_afifo TMI_IN_WR_DATA<17>
Project.unit<0>.dataChannel<69>=u0_tmi_afifo TMI_IN_WR_DATA<18>
Project.unit<0>.dataChannel<6>=u0_tmi_afifo TMI_IN_IDLE
Project.unit<0>.dataChannel<70>=u0_tmi_afifo TMI_IN_WR_DATA<19>
Project.unit<0>.dataChannel<71>=u0_tmi_afifo TMI_IN_WR_DATA<20>
Project.unit<0>.dataChannel<72>=u0_tmi_afifo TMI_IN_WR_DATA<21>
Project.unit<0>.dataChannel<73>=u0_tmi_afifo TMI_IN_WR_DATA<22>
Project.unit<0>.dataChannel<74>=u0_tmi_afifo TMI_IN_WR_DATA<23>
Project.unit<0>.dataChannel<75>=u0_tmi_afifo TMI_IN_WR_DATA<24>
Project.unit<0>.dataChannel<76>=u0_tmi_afifo TMI_IN_WR_DATA<25>
Project.unit<0>.dataChannel<77>=u0_tmi_afifo TMI_IN_WR_DATA<26>
Project.unit<0>.dataChannel<78>=u0_tmi_afifo TMI_IN_WR_DATA<27>
Project.unit<0>.dataChannel<79>=u0_tmi_afifo TMI_IN_WR_DATA<28>
Project.unit<0>.dataChannel<7>=u0_tmi_afifo TMI_IN_RNW
Project.unit<0>.dataChannel<80>=u0_tmi_afifo TMI_IN_WR_DATA<29>
Project.unit<0>.dataChannel<81>=u0_tmi_afifo TMI_IN_WR_DATA<30>
Project.unit<0>.dataChannel<82>=u0_tmi_afifo TMI_IN_WR_DATA<31>
Project.unit<0>.dataChannel<83>=u0_tmi_afifo TMI_OUT_DVAL
Project.unit<0>.dataChannel<84>=u0_tmi_afifo TMI_OUT_BUSY
Project.unit<0>.dataChannel<85>=u0_tmi_afifo TMI_OUT_IDLE
Project.unit<0>.dataChannel<86>=u0_tmi_afifo TMI_OUT_ADD<0>
Project.unit<0>.dataChannel<87>=u0_tmi_afifo TMI_OUT_ADD<1>
Project.unit<0>.dataChannel<88>=u0_tmi_afifo TMI_OUT_ADD<2>
Project.unit<0>.dataChannel<89>=u0_tmi_afifo TMI_OUT_ADD<3>
Project.unit<0>.dataChannel<8>=u0_tmi_afifo TMI_IN_BUSY
Project.unit<0>.dataChannel<90>=u0_tmi_afifo TMI_OUT_ADD<4>
Project.unit<0>.dataChannel<91>=u0_tmi_afifo TMI_OUT_ADD<5>
Project.unit<0>.dataChannel<92>=u0_tmi_afifo TMI_OUT_ADD<6>
Project.unit<0>.dataChannel<93>=u0_tmi_afifo TMI_OUT_ADD<7>
Project.unit<0>.dataChannel<94>=u0_tmi_afifo TMI_OUT_RNW
Project.unit<0>.dataChannel<95>=u0_tmi_afifo TMI_OUT_RD_DATA<0>
Project.unit<0>.dataChannel<96>=u0_tmi_afifo TMI_OUT_RD_DATA<1>
Project.unit<0>.dataChannel<97>=u0_tmi_afifo TMI_OUT_RD_DATA<2>
Project.unit<0>.dataChannel<98>=u0_tmi_afifo TMI_OUT_RD_DATA<3>
Project.unit<0>.dataChannel<99>=u0_tmi_afifo TMI_OUT_RD_DATA<4>
Project.unit<0>.dataChannel<9>=u0_tmi_afifo TMI_IN_ERROR
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=162
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=tmi_arst_s
Project.unit<0>.triggerChannel<0><100>=u0_tmi_afifo TMI_OUT_RD_DATA<5>
Project.unit<0>.triggerChannel<0><101>=u0_tmi_afifo TMI_OUT_RD_DATA<6>
Project.unit<0>.triggerChannel<0><102>=u0_tmi_afifo TMI_OUT_RD_DATA<7>
Project.unit<0>.triggerChannel<0><103>=u0_tmi_afifo TMI_OUT_RD_DATA<8>
Project.unit<0>.triggerChannel<0><104>=u0_tmi_afifo TMI_OUT_RD_DATA<9>
Project.unit<0>.triggerChannel<0><105>=u0_tmi_afifo TMI_OUT_RD_DATA<10>
Project.unit<0>.triggerChannel<0><106>=u0_tmi_afifo TMI_OUT_RD_DATA<11>
Project.unit<0>.triggerChannel<0><107>=u0_tmi_afifo TMI_OUT_RD_DATA<12>
Project.unit<0>.triggerChannel<0><108>=u0_tmi_afifo TMI_OUT_RD_DATA<13>
Project.unit<0>.triggerChannel<0><109>=u0_tmi_afifo TMI_OUT_RD_DATA<14>
Project.unit<0>.triggerChannel<0><10>=u0_tmi_afifo TMI_IN_ADD<0>
Project.unit<0>.triggerChannel<0><110>=u0_tmi_afifo TMI_OUT_RD_DATA<15>
Project.unit<0>.triggerChannel<0><111>=u0_tmi_afifo TMI_OUT_RD_DATA<16>
Project.unit<0>.triggerChannel<0><112>=u0_tmi_afifo TMI_OUT_RD_DATA<17>
Project.unit<0>.triggerChannel<0><113>=u0_tmi_afifo TMI_OUT_RD_DATA<18>
Project.unit<0>.triggerChannel<0><114>=u0_tmi_afifo TMI_OUT_RD_DATA<19>
Project.unit<0>.triggerChannel<0><115>=u0_tmi_afifo TMI_OUT_RD_DATA<20>
Project.unit<0>.triggerChannel<0><116>=u0_tmi_afifo TMI_OUT_RD_DATA<21>
Project.unit<0>.triggerChannel<0><117>=u0_tmi_afifo TMI_OUT_RD_DATA<22>
Project.unit<0>.triggerChannel<0><118>=u0_tmi_afifo TMI_OUT_RD_DATA<23>
Project.unit<0>.triggerChannel<0><119>=u0_tmi_afifo TMI_OUT_RD_DATA<24>
Project.unit<0>.triggerChannel<0><11>=u0_tmi_afifo TMI_IN_ADD<1>
Project.unit<0>.triggerChannel<0><120>=u0_tmi_afifo TMI_OUT_RD_DATA<25>
Project.unit<0>.triggerChannel<0><121>=u0_tmi_afifo TMI_OUT_RD_DATA<26>
Project.unit<0>.triggerChannel<0><122>=u0_tmi_afifo TMI_OUT_RD_DATA<27>
Project.unit<0>.triggerChannel<0><123>=u0_tmi_afifo TMI_OUT_RD_DATA<28>
Project.unit<0>.triggerChannel<0><124>=u0_tmi_afifo TMI_OUT_RD_DATA<29>
Project.unit<0>.triggerChannel<0><125>=u0_tmi_afifo TMI_OUT_RD_DATA<30>
Project.unit<0>.triggerChannel<0><126>=u0_tmi_afifo TMI_OUT_RD_DATA<31>
Project.unit<0>.triggerChannel<0><127>=u0_tmi_afifo TMI_OUT_RD_DVAL
Project.unit<0>.triggerChannel<0><128>=u0_tmi_afifo TMI_OUT_WR_DATA<0>
Project.unit<0>.triggerChannel<0><129>=u0_tmi_afifo TMI_OUT_WR_DATA<1>
Project.unit<0>.triggerChannel<0><12>=u0_tmi_afifo TMI_IN_ADD<2>
Project.unit<0>.triggerChannel<0><130>=u0_tmi_afifo TMI_OUT_WR_DATA<2>
Project.unit<0>.triggerChannel<0><131>=u0_tmi_afifo TMI_OUT_WR_DATA<3>
Project.unit<0>.triggerChannel<0><132>=u0_tmi_afifo TMI_OUT_WR_DATA<4>
Project.unit<0>.triggerChannel<0><133>=u0_tmi_afifo TMI_OUT_WR_DATA<5>
Project.unit<0>.triggerChannel<0><134>=u0_tmi_afifo TMI_OUT_WR_DATA<6>
Project.unit<0>.triggerChannel<0><135>=u0_tmi_afifo TMI_OUT_WR_DATA<7>
Project.unit<0>.triggerChannel<0><136>=u0_tmi_afifo TMI_OUT_WR_DATA<8>
Project.unit<0>.triggerChannel<0><137>=u0_tmi_afifo TMI_OUT_WR_DATA<9>
Project.unit<0>.triggerChannel<0><138>=u0_tmi_afifo TMI_OUT_WR_DATA<10>
Project.unit<0>.triggerChannel<0><139>=u0_tmi_afifo TMI_OUT_WR_DATA<11>
Project.unit<0>.triggerChannel<0><13>=u0_tmi_afifo TMI_IN_ADD<3>
Project.unit<0>.triggerChannel<0><140>=u0_tmi_afifo TMI_OUT_WR_DATA<12>
Project.unit<0>.triggerChannel<0><141>=u0_tmi_afifo TMI_OUT_WR_DATA<13>
Project.unit<0>.triggerChannel<0><142>=u0_tmi_afifo TMI_OUT_WR_DATA<14>
Project.unit<0>.triggerChannel<0><143>=u0_tmi_afifo TMI_OUT_WR_DATA<15>
Project.unit<0>.triggerChannel<0><144>=u0_tmi_afifo TMI_OUT_WR_DATA<16>
Project.unit<0>.triggerChannel<0><145>=u0_tmi_afifo TMI_OUT_WR_DATA<17>
Project.unit<0>.triggerChannel<0><146>=u0_tmi_afifo TMI_OUT_WR_DATA<18>
Project.unit<0>.triggerChannel<0><147>=u0_tmi_afifo TMI_OUT_WR_DATA<19>
Project.unit<0>.triggerChannel<0><148>=u0_tmi_afifo TMI_OUT_WR_DATA<20>
Project.unit<0>.triggerChannel<0><149>=u0_tmi_afifo TMI_OUT_WR_DATA<21>
Project.unit<0>.triggerChannel<0><14>=u0_tmi_afifo TMI_IN_ADD<4>
Project.unit<0>.triggerChannel<0><150>=u0_tmi_afifo TMI_OUT_WR_DATA<22>
Project.unit<0>.triggerChannel<0><151>=u0_tmi_afifo TMI_OUT_WR_DATA<23>
Project.unit<0>.triggerChannel<0><152>=u0_tmi_afifo TMI_OUT_WR_DATA<24>
Project.unit<0>.triggerChannel<0><153>=u0_tmi_afifo TMI_OUT_WR_DATA<25>
Project.unit<0>.triggerChannel<0><154>=u0_tmi_afifo TMI_OUT_WR_DATA<26>
Project.unit<0>.triggerChannel<0><155>=u0_tmi_afifo TMI_OUT_WR_DATA<27>
Project.unit<0>.triggerChannel<0><156>=u0_tmi_afifo TMI_OUT_WR_DATA<28>
Project.unit<0>.triggerChannel<0><157>=u0_tmi_afifo TMI_OUT_WR_DATA<29>
Project.unit<0>.triggerChannel<0><158>=u0_tmi_afifo TMI_OUT_WR_DATA<30>
Project.unit<0>.triggerChannel<0><159>=u0_tmi_afifo TMI_OUT_WR_DATA<31>
Project.unit<0>.triggerChannel<0><15>=u0_tmi_afifo TMI_IN_ADD<5>
Project.unit<0>.triggerChannel<0><160>=err_flag_s<0>
Project.unit<0>.triggerChannel<0><161>=err_flag_s<1>
Project.unit<0>.triggerChannel<0><16>=u0_tmi_afifo TMI_IN_ADD<6>
Project.unit<0>.triggerChannel<0><17>=u0_tmi_afifo TMI_IN_ADD<7>
Project.unit<0>.triggerChannel<0><18>=u0_tmi_afifo TMI_IN_RD_DATA<0>
Project.unit<0>.triggerChannel<0><19>=u0_tmi_afifo TMI_IN_RD_DATA<1>
Project.unit<0>.triggerChannel<0><1>=tmi_arst_Fedge
Project.unit<0>.triggerChannel<0><20>=u0_tmi_afifo TMI_IN_RD_DATA<2>
Project.unit<0>.triggerChannel<0><21>=u0_tmi_afifo TMI_IN_RD_DATA<3>
Project.unit<0>.triggerChannel<0><22>=u0_tmi_afifo TMI_IN_RD_DATA<4>
Project.unit<0>.triggerChannel<0><23>=u0_tmi_afifo TMI_IN_RD_DATA<5>
Project.unit<0>.triggerChannel<0><24>=u0_tmi_afifo TMI_IN_RD_DATA<6>
Project.unit<0>.triggerChannel<0><25>=u0_tmi_afifo TMI_IN_RD_DATA<7>
Project.unit<0>.triggerChannel<0><26>=u0_tmi_afifo TMI_IN_RD_DATA<8>
Project.unit<0>.triggerChannel<0><27>=u0_tmi_afifo TMI_IN_RD_DATA<9>
Project.unit<0>.triggerChannel<0><28>=u0_tmi_afifo TMI_IN_RD_DATA<10>
Project.unit<0>.triggerChannel<0><29>=u0_tmi_afifo TMI_IN_RD_DATA<11>
Project.unit<0>.triggerChannel<0><2>=start_test_s
Project.unit<0>.triggerChannel<0><30>=u0_tmi_afifo TMI_IN_RD_DATA<12>
Project.unit<0>.triggerChannel<0><31>=u0_tmi_afifo TMI_IN_RD_DATA<13>
Project.unit<0>.triggerChannel<0><32>=u0_tmi_afifo TMI_IN_RD_DATA<14>
Project.unit<0>.triggerChannel<0><33>=u0_tmi_afifo TMI_IN_RD_DATA<15>
Project.unit<0>.triggerChannel<0><34>=u0_tmi_afifo TMI_IN_RD_DATA<16>
Project.unit<0>.triggerChannel<0><35>=u0_tmi_afifo TMI_IN_RD_DATA<17>
Project.unit<0>.triggerChannel<0><36>=u0_tmi_afifo TMI_IN_RD_DATA<18>
Project.unit<0>.triggerChannel<0><37>=u0_tmi_afifo TMI_IN_RD_DATA<19>
Project.unit<0>.triggerChannel<0><38>=u0_tmi_afifo TMI_IN_RD_DATA<20>
Project.unit<0>.triggerChannel<0><39>=u0_tmi_afifo TMI_IN_RD_DATA<21>
Project.unit<0>.triggerChannel<0><3>=u0_TMI_memtest TEST_DONE
Project.unit<0>.triggerChannel<0><40>=u0_tmi_afifo TMI_IN_RD_DATA<22>
Project.unit<0>.triggerChannel<0><41>=u0_tmi_afifo TMI_IN_RD_DATA<23>
Project.unit<0>.triggerChannel<0><42>=u0_tmi_afifo TMI_IN_RD_DATA<24>
Project.unit<0>.triggerChannel<0><43>=u0_tmi_afifo TMI_IN_RD_DATA<25>
Project.unit<0>.triggerChannel<0><44>=u0_tmi_afifo TMI_IN_RD_DATA<26>
Project.unit<0>.triggerChannel<0><45>=u0_tmi_afifo TMI_IN_RD_DATA<27>
Project.unit<0>.triggerChannel<0><46>=u0_tmi_afifo TMI_IN_RD_DATA<28>
Project.unit<0>.triggerChannel<0><47>=u0_tmi_afifo TMI_IN_RD_DATA<29>
Project.unit<0>.triggerChannel<0><48>=u0_tmi_afifo TMI_IN_RD_DATA<30>
Project.unit<0>.triggerChannel<0><49>=u0_tmi_afifo TMI_IN_RD_DATA<31>
Project.unit<0>.triggerChannel<0><4>=u0_TMI_memtest TEST_PASS
Project.unit<0>.triggerChannel<0><50>=u0_tmi_afifo TMI_IN_RD_DVAL
Project.unit<0>.triggerChannel<0><51>=u0_tmi_afifo TMI_IN_WR_DATA<0>
Project.unit<0>.triggerChannel<0><52>=u0_tmi_afifo TMI_IN_WR_DATA<1>
Project.unit<0>.triggerChannel<0><53>=u0_tmi_afifo TMI_IN_WR_DATA<2>
Project.unit<0>.triggerChannel<0><54>=u0_tmi_afifo TMI_IN_WR_DATA<3>
Project.unit<0>.triggerChannel<0><55>=u0_tmi_afifo TMI_IN_WR_DATA<4>
Project.unit<0>.triggerChannel<0><56>=u0_tmi_afifo TMI_IN_WR_DATA<5>
Project.unit<0>.triggerChannel<0><57>=u0_tmi_afifo TMI_IN_WR_DATA<6>
Project.unit<0>.triggerChannel<0><58>=u0_tmi_afifo TMI_IN_WR_DATA<7>
Project.unit<0>.triggerChannel<0><59>=u0_tmi_afifo TMI_IN_WR_DATA<8>
Project.unit<0>.triggerChannel<0><5>=u0_tmi_afifo TMI_IN_DVAL
Project.unit<0>.triggerChannel<0><60>=u0_tmi_afifo TMI_IN_WR_DATA<9>
Project.unit<0>.triggerChannel<0><61>=u0_tmi_afifo TMI_IN_WR_DATA<10>
Project.unit<0>.triggerChannel<0><62>=u0_tmi_afifo TMI_IN_WR_DATA<11>
Project.unit<0>.triggerChannel<0><63>=u0_tmi_afifo TMI_IN_WR_DATA<12>
Project.unit<0>.triggerChannel<0><64>=u0_tmi_afifo TMI_IN_WR_DATA<13>
Project.unit<0>.triggerChannel<0><65>=u0_tmi_afifo TMI_IN_WR_DATA<14>
Project.unit<0>.triggerChannel<0><66>=u0_tmi_afifo TMI_IN_WR_DATA<15>
Project.unit<0>.triggerChannel<0><67>=u0_tmi_afifo TMI_IN_WR_DATA<16>
Project.unit<0>.triggerChannel<0><68>=u0_tmi_afifo TMI_IN_WR_DATA<17>
Project.unit<0>.triggerChannel<0><69>=u0_tmi_afifo TMI_IN_WR_DATA<18>
Project.unit<0>.triggerChannel<0><6>=u0_tmi_afifo TMI_IN_IDLE
Project.unit<0>.triggerChannel<0><70>=u0_tmi_afifo TMI_IN_WR_DATA<19>
Project.unit<0>.triggerChannel<0><71>=u0_tmi_afifo TMI_IN_WR_DATA<20>
Project.unit<0>.triggerChannel<0><72>=u0_tmi_afifo TMI_IN_WR_DATA<21>
Project.unit<0>.triggerChannel<0><73>=u0_tmi_afifo TMI_IN_WR_DATA<22>
Project.unit<0>.triggerChannel<0><74>=u0_tmi_afifo TMI_IN_WR_DATA<23>
Project.unit<0>.triggerChannel<0><75>=u0_tmi_afifo TMI_IN_WR_DATA<24>
Project.unit<0>.triggerChannel<0><76>=u0_tmi_afifo TMI_IN_WR_DATA<25>
Project.unit<0>.triggerChannel<0><77>=u0_tmi_afifo TMI_IN_WR_DATA<26>
Project.unit<0>.triggerChannel<0><78>=u0_tmi_afifo TMI_IN_WR_DATA<27>
Project.unit<0>.triggerChannel<0><79>=u0_tmi_afifo TMI_IN_WR_DATA<28>
Project.unit<0>.triggerChannel<0><7>=u0_tmi_afifo TMI_IN_RNW
Project.unit<0>.triggerChannel<0><80>=u0_tmi_afifo TMI_IN_WR_DATA<29>
Project.unit<0>.triggerChannel<0><81>=u0_tmi_afifo TMI_IN_WR_DATA<30>
Project.unit<0>.triggerChannel<0><82>=u0_tmi_afifo TMI_IN_WR_DATA<31>
Project.unit<0>.triggerChannel<0><83>=u0_tmi_afifo TMI_OUT_DVAL
Project.unit<0>.triggerChannel<0><84>=u0_tmi_afifo TMI_OUT_BUSY
Project.unit<0>.triggerChannel<0><85>=u0_tmi_afifo TMI_OUT_IDLE
Project.unit<0>.triggerChannel<0><86>=u0_tmi_afifo TMI_OUT_ADD<0>
Project.unit<0>.triggerChannel<0><87>=u0_tmi_afifo TMI_OUT_ADD<1>
Project.unit<0>.triggerChannel<0><88>=u0_tmi_afifo TMI_OUT_ADD<2>
Project.unit<0>.triggerChannel<0><89>=u0_tmi_afifo TMI_OUT_ADD<3>
Project.unit<0>.triggerChannel<0><8>=u0_tmi_afifo TMI_IN_BUSY
Project.unit<0>.triggerChannel<0><90>=u0_tmi_afifo TMI_OUT_ADD<4>
Project.unit<0>.triggerChannel<0><91>=u0_tmi_afifo TMI_OUT_ADD<5>
Project.unit<0>.triggerChannel<0><92>=u0_tmi_afifo TMI_OUT_ADD<6>
Project.unit<0>.triggerChannel<0><93>=u0_tmi_afifo TMI_OUT_ADD<7>
Project.unit<0>.triggerChannel<0><94>=u0_tmi_afifo TMI_OUT_RNW
Project.unit<0>.triggerChannel<0><95>=u0_tmi_afifo TMI_OUT_RD_DATA<0>
Project.unit<0>.triggerChannel<0><96>=u0_tmi_afifo TMI_OUT_RD_DATA<1>
Project.unit<0>.triggerChannel<0><97>=u0_tmi_afifo TMI_OUT_RD_DATA<2>
Project.unit<0>.triggerChannel<0><98>=u0_tmi_afifo TMI_OUT_RD_DATA<3>
Project.unit<0>.triggerChannel<0><99>=u0_tmi_afifo TMI_OUT_RD_DATA<4>
Project.unit<0>.triggerChannel<0><9>=u0_tmi_afifo TMI_IN_ERROR
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=162
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
