--------------------------------------------------------------------------------
-- Copyright (c) 1995-2003 Xilinx, Inc.
-- All Right Reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 7.1i
--  \   \         Application : 
--  /   /         Filename : dcm_caml.vhd
-- /___/   /\     Timestamp : 09/23/2005 17:00:28
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: 
--Design Name: dcm_caml
--
-- Module dcm_caml
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
-- synopsys translate_off
library unisim;
use unisim.vcomponents.ALL;
-- synopsys translate_on
library common_hdl;

entity dcm_caml is
   generic(
      EXT_CLK_SRC : boolean := false);        -- false uses internal system clock divided by 2
   port(
      CLKIN_EXT       : in    std_logic;
      CLKIN_SYS       : in    std_logic;
      RST_IN          : in    std_logic;           
      CLK0_OUT        : out   std_logic; 
      CLK90_OUT       : out   std_logic; 
      CLK180_OUT      : out   std_logic; 
      CLK270_OUT      : out   std_logic; 
      LOCKED_OUT      : out   std_logic);
end dcm_caml;

architecture BEHAVIORAL of dcm_caml is
   
   constant DIV_TWO       : boolean := not EXT_CLK_SRC;
   constant GND           : std_logic := '0';
   
   signal CLKIN           : std_logic;
   signal CLKFB_IN        : std_logic;   
   signal CLK0_BUF        : std_logic;
   signal CLK90_BUF       : std_logic;
   signal CLK180_BUF      : std_logic;
   signal CLK270_BUF      : std_logic;
   signal reset_local     : std_logic;
   
   component DCM_RESET
      port (
         CLK  : in std_logic;
         RST_IN  : in std_logic;
         DCM_RST : out std_logic);
   end component;
   
   component BUFG
      port ( I : in    std_logic; 
         O : out   std_logic);
   end component;
   
   component DCM
      generic(
         CLK_FEEDBACK : string :=  "1X";
         CLKDV_DIVIDE : real :=  2.000000;
         CLKFX_DIVIDE : integer :=  1;
         CLKFX_MULTIPLY : integer :=  4;
         CLKIN_DIVIDE_BY_2 : boolean :=  FALSE;
         CLKIN_PERIOD : real :=  10.000000;
         CLKOUT_PHASE_SHIFT : string :=  "NONE";
         DESKEW_ADJUST : string :=  "SYSTEM_SYNCHRONOUS";
         DFS_FREQUENCY_MODE : string :=  "LOW";
         DLL_FREQUENCY_MODE : string :=  "LOW";
         DUTY_CYCLE_CORRECTION : boolean :=  TRUE;
         FACTORY_JF : bit_vector :=  x"C080";
         PHASE_SHIFT : integer :=  0;
         STARTUP_WAIT : boolean :=  FALSE;
         DSS_MODE : string :=  "NONE");
      port(
         CLKIN    : in    std_logic; 
         CLKFB    : in    std_logic; 
         RST      : in    std_logic; 
         PSEN     : in    std_logic; 
         PSINCDEC : in    std_logic; 
         PSCLK    : in    std_logic; 
         DSSEN    : in    std_logic; 
         CLK0     : out   std_logic; 
         CLK90    : out   std_logic; 
         CLK180   : out   std_logic; 
         CLK270   : out   std_logic; 
         CLKDV    : out   std_logic; 
         CLK2X    : out   std_logic; 
         CLK2X180 : out   std_logic; 
         CLKFX    : out   std_logic; 
         CLKFX180 : out   std_logic; 
         STATUS   : out   std_logic_vector (7 downto 0); 
         LOCKED   : out   std_logic; 
         PSDONE   : out   std_logic);
   end component;
   
begin
   
   -- CLink Clock derived from external crystal
   clkin_ext_gen : if EXT_CLK_SRC generate
      CLKIN <= CLKIN_EXT;
   end generate;
   
   -- CLink Clock derived from system clock divided by 2
   clkin_sys_gen : if not EXT_CLK_SRC generate
      CLKIN <= CLKIN_SYS;
   end generate;
   
   -- Global Clock Buffers
   CLK0_BUFG_INST : BUFG
   port map (I=>CLK0_BUF,
      O=>CLKFB_IN);  
   
   CLK90_BUFG_INST : BUFG
   port map (I=>CLK90_BUF,
      O=>CLK90_OUT);   
   
   CLK180_BUFG_INST : BUFG
   port map (I=>CLK180_BUF,
      O=>CLK180_OUT);  
   
   CLK270_BUFG_INST : BUFG
   port map (I=>CLK270_BUF,
      O=>CLK270_OUT);   
   
   -- Output Mapping
   CLK0_OUT <= CLKFB_IN;
   
   -- DCM instantiation
   DCM_INST : DCM
   generic map(
   CLK_FEEDBACK => "1X",
   CLKDV_DIVIDE => 2.000000,
   CLKFX_DIVIDE => 1,
   CLKFX_MULTIPLY => 4,
   CLKIN_DIVIDE_BY_2 => DIV_TWO,
   CLKIN_PERIOD => 10.000000,
   CLKOUT_PHASE_SHIFT => "NONE",
   DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
   DFS_FREQUENCY_MODE => "LOW",
   DLL_FREQUENCY_MODE => "LOW",
   DUTY_CYCLE_CORRECTION => TRUE,
   FACTORY_JF => x"C080",
   PHASE_SHIFT => 0,
   STARTUP_WAIT => FALSE)
   port map(
      CLKFB => CLKFB_IN,
      CLKIN => CLKIN,
      DSSEN => gnd,
      PSCLK => gnd,
      PSEN => gnd,
      PSINCDEC => gnd,
      RST => reset_local,
      CLKDV => open,
      CLKFX => open,
      CLKFX180 => open,
      CLK0 => CLK0_BUF,
      CLK2X => open,
      CLK2X180 => open,
      CLK90 => CLK90_BUF,
      CLK180 => CLK180_BUF,
      CLK270 => CLK270_BUF,
      LOCKED => LOCKED_OUT,
      PSDONE => open,
      STATUS => open);
   
   -- manage the reset circuit
   inst_dcm_reset : dcm_reset port map(CLK => CLKIN, RST_IN => RST_IN, DCM_RST => reset_local);
   
end BEHAVIORAL;


