#savealltabs
#adel -all
#setactivelib work
#clearlibrary 	

#signal stat
acom \
 "$FIR251PROC/src/Trig/HDL/trig_define.vhd" \
 "$FIR251COMMON/VHDL/signal_stat/min_max_define.vhd" \
 "$FIR251COMMON/VHDL/signal_stat/min_max_ctrl.vhd" \
 "$FIR251COMMON/VHDL/signal_stat/delay_measurement.vhd" \
 "$FIR251COMMON/VHDL/signal_stat/trig_delay.bde" \
 "$FIR251COMMON/VHDL/signal_stat/period_duration.vhd" \
 "$FIR251COMMON/VHDL/signal_stat/trig_period.bde" \
 "$FIR251COMMON/VHDL/signal_stat/trig_period_8ch.bde"
 
# sources FPa common 
acom -relax $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/ad5648_driver.vhd 
acom -nowarn DAGGEN_0523 -incr \
 $COMMON_HDL/SPI/ads1118_driver.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/signal_filter.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_trig_controller.vhd  \
 $FIR251PROC/src/FPA/fpa_trig_precontroller.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/dfpa_hardw_stat_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_intf_sequencer.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_status_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/brd_id_reader.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/adc_brd_id_reader.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/ddc_brd_id_reader.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/flex_brd_id_reader.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/LL8_ext_to_spi_tx.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/LL8_ext_to_spi_tx_v2.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/adc_brd_switch_ctrl.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/monitoring_adc_ctrl.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/spi_mux_ctler.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/spi_mux_ctler_sadc.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_services_ctrl.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_sample_counter.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_mux.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_int_signal_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_sample_mean.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_sample_selector.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_sample_sum.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_dispatcher.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_diag_line_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_real_mode_dval_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_diag_data_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_flow_mux.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/concat_1_to_8.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/LL8_ext_fifo8.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_hw_driver_ctrler.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fleg_prog_ctler_kernel.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fleG_dac_spi_feeder.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_chn_diversity_ctrler.vhd \
 $FIR251PROC/src/Quad_serdes/HDL/quad_adc_ctrl.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_ctrl_map.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_line_sync_mode_dval_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_sample_demux.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_elec_ref_ctrler.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_elec_ref_calc.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/LL_ext_sync_flow.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_quad_add.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_quad_subtract.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_quad_mult.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_single_div_ip_wrapper.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_low_saturation.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_high_saturation.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/frm_in_progress_gen.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_data_cnt.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_min_max_ctrl.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/edge_counter.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_prog_mux.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/dfpa_cfg_dpram_writer.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_readout_flags_delay.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_real_data_gen_v2.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_min_max_ctrl.vhd \
 $FIR251COMMON/VHDL/signal_stat/high_duration.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_clipper.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_scaler.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_dyn_range_ctrl.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_signal_length_min_max.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_dval_gen_v2.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_data_cnt_min_max.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fpa_watchdog_module.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_saturation_ctrl.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_quad_div.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_elec_ref_proc.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_analog_chain_corr.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_real_data_gen.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_dval_gen.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_hsample_proc.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_vsample_proc.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_pix_pos.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_pix_sel.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_cropping_core.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_cropping.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_line_pos.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_offset_corr_core.vhd \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_offset_corr.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_ctrl.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_ctrl_v2.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_ctrl_16chn.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_data_ctrl_16chn_v2.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_services.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/afpa_services_sadc.bde \
 $COMMON_HDL/Common_Projects/TEL2000/FPA_common/src/fleG_prog_ctrler.bde
