@onerror
{
goto end
}

savealltabs
SetActiveLib -work
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_parameters_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_wr_data_fifo_16.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_wr_data_fifo_8.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_rd_wr_addr_fifo_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_backend_fifos_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_controller_iobs_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_v4_dq_iob.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_v4_dqs_iob.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_data_path_iobs_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_data_tap_inc.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_data_write_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_ddr_controller_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_idelay_ctrl.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_infrastructure.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_infrastructure_iobs_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_iobs_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_pattern_compare4.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_RAM_D_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_rd_data_fifo_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_rd_data_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_tap_ctrl_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_tap_logic_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_user_interface_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_data_path_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top_top_0.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\MIG\mem_interface_top.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Tester\dat_gen.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Tester\dat_path.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Tester\ddr_test_sm.asf"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Tester\adr_gen.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Tester\mctrl_iface.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Tester\ddr_tester.bde"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\User-Interface\DDR_Interface_FSM.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\User-Interface\DDR_Interface.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\User-Interface\ddr_block.bde"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\User-Interface\ddr_top.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\NGC\ddr_wrapper_128d_26a_r1.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\NGC\ddr_wrapper_128d_27a_r1.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Model\DDR_define.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Model\DDR_Command_Decoder.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Model\DDR_Registers.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Model\mt46v128m4.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\Model\MT36VDDF25672G.bde"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\TestBench\intf_acces_gen_ml461.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\TestBench\mem_acces_gen.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\TestBench\ddr_mig_ml461.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\TestBench\ddr_tb_ml461.vhd"
acom  -work ml_461 "D:\telops\Common_HDL\DDR_Ctrl\src\TestBench\ddr_tb_cfg_ml461.vhd"
label end
