  --------------------------------------------------------------------------------
-- Copyright (c) 1995-2007 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 9.1.03i
--  \   \         Application : xaw2vhdl
--  /   /         Filename : zbt_clocks_extern.vhd
-- /___/   /\     Timestamp : 04/30/2007 10:53:07
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st D:\Telops\FIR-00186\src\Clocks\zbt_clocks_extern.xaw D:\Telops\FIR-00186\src\Clocks\zbt_clocks_extern
--Design Name: zbt_clocks_extern
--Device: xc4vfx12-sf363-10
--
-- Module zbt_clocks_extern
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;       
library Common_HDL;   
use Common_HDL.all;

entity clk160_dcm is
   port (
          CLK_IN          : in    std_logic; 
          RST_IN          : in    std_logic; 
          CLK_EXT         : out   std_logic; 
          DCM_NOT_LOCKED  : out   std_logic);
end clk160_dcm;                 
--
---- translate_off
--architecture asim of locallink_clk_dcm is
--   constant CLK_PERIOD : time := 6.25 ns;
--   signal CLK_i : std_logic := '0';
--begin    
--   CLK_EXT <= CLK_i;
--   --CLK_EXT2 <= CLK_i;
--   
--   CLK_GEN: process(CLK_i)
--   begin
--   	CLK_i <= not CLK_i after CLK_PERIOD/2; 
--   end process;   
--   
--   clock_proc : process (RST_IN, CLK_IN)
--      variable delay : integer range 0 to 31 := 0;
--   begin          
--      if RST_IN = '1' then
--         DCM_NOT_LOCKED <= '1';
--      elsif rising_edge(CLK_IN) then
--         if delay < 31 then
--            delay := delay + 1;
--         end if;                                
--         if delay > 23 then
--            DCM_NOT_LOCKED <= '0';
--         else              
--            DCM_NOT_LOCKED <= '1';
--         end if;     
--      end if;      
--   end process;    
--end asim;        
---- translate_on

architecture BEHAVIORAL of clk160_dcm is
   signal dcm_rst         : std_logic;
   signal dcm_locked      : std_logic;
   signal CLKFX_BUF       : std_logic;   
   signal CLK0_BUF        : std_logic;
   signal CLK0_BUFG       : std_logic;
   signal CLKFX_BUFG      : std_logic;
   signal GND_BIT         : std_logic;
   signal GND_BUS_7       : std_logic_vector (6 downto 0);
   signal GND_BUS_16      : std_logic_vector (15 downto 0);
   signal VCC_BIT         : std_logic;
   component BUFG
      port ( I : in    std_logic; 
             O : out   std_logic);
   end component;
   
   component IBUFG
      port ( I : in    std_logic; 
             O : out   std_logic);
   end component;     
   
	-- Component declaration of the "dcm_reset(rtl)" unit defined in
	-- file: "./../Utilities/dcm_reset.vhd"
	component dcm_reset
	port(
		RST_IN : in std_logic;
		DCM_RST : out std_logic;
		CLK : in std_logic);
	end component;
   
   
   -- Period Jitter (unit interval) for block DCM_ADV_INST = 0.022 UI
   -- Period Jitter (Peak-to-Peak) for block DCM_ADV_INST = 0.109 ns
   component DCM_ADV
      generic( CLK_FEEDBACK : string :=  "1X";
               CLKDV_DIVIDE : real :=  2.0;
               CLKFX_DIVIDE : integer :=  1;
               CLKFX_MULTIPLY : integer :=  4;
               CLKIN_DIVIDE_BY_2 : boolean :=  FALSE;
               CLKIN_PERIOD : real :=  10.0;             
               CLKOUT_PHASE_SHIFT : string :=  "NONE";
               DCM_AUTOCALIBRATION : boolean :=  TRUE;
               DCM_PERFORMANCE_MODE : string :=  "MAX_SPEED";
               DESKEW_ADJUST : string :=  "SYSTEM_SYNCHRONOUS";
               DFS_FREQUENCY_MODE : string :=  "LOW";
               DLL_FREQUENCY_MODE : string :=  "LOW";
               DUTY_CYCLE_CORRECTION : boolean :=  TRUE;
               FACTORY_JF : bit_vector :=  x"F0F0";
               PHASE_SHIFT : integer :=  0;
               STARTUP_WAIT : boolean :=  FALSE;
               SIM_DEVICE : string :=  "VIRTEX4");
      port ( CLKIN    : in    std_logic; 
             CLKFB    : in    std_logic; 
             DADDR    : in    std_logic_vector (6 downto 0); 
             DI       : in    std_logic_vector (15 downto 0); 
             DWE      : in    std_logic; 
             DEN      : in    std_logic; 
             DCLK     : in    std_logic; 
             RST      : in    std_logic; 
             PSEN     : in    std_logic; 
             PSINCDEC : in    std_logic; 
             PSCLK    : in    std_logic; 
             CLK0     : out   std_logic; 
             CLK90    : out   std_logic; 
             CLK180   : out   std_logic; 
             CLK270   : out   std_logic; 
             CLKDV    : out   std_logic; 
             CLK2X    : out   std_logic; 
             CLK2X180 : out   std_logic; 
             CLKFX    : out   std_logic; 
             CLKFX180 : out   std_logic; 
             DRDY     : out   std_logic; 
             DO       : out   std_logic_vector (15 downto 0); 
             LOCKED   : out   std_logic; 
             PSDONE   : out   std_logic);
   end component;
   
   component ODDR
      generic( INIT : bit :=  '0';
               DDR_CLK_EDGE : string :=  "OPPOSITE_EDGE";
               SRTYPE : string :=  "SYNC");
      port ( D1 : in    std_logic; 
             D2 : in    std_logic; 
             CE : in    std_logic; 
             C  : in    std_logic; 
             S  : in    std_logic; 
             R  : in    std_logic; 
             Q  : out   std_logic);
   end component;       
     
   
begin                             
the_dcm_reset : dcm_reset  
   port map(
      RST_IN => RST_IN,
      DCM_RST => dcm_rst,
      CLK => CLK_IN
   );   
   
   CLK_EXT <= CLKFX_BUFG;
   DCM_NOT_LOCKED <= not dcm_locked;
   GND_BIT <= '0';
   GND_BUS_7(6 downto 0) <= "0000000";
   GND_BUS_16(15 downto 0) <= "0000000000000000";
   VCC_BIT <= '1';
   
   CLKFX_BUFG_INST : BUFG
      port map (I=>CLKFX_BUF,
                O=>CLKFX_BUFG);
     
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLK0_BUFG);
   
   DCM_ADV_INST : DCM_ADV
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 5,
            CLKFX_MULTIPLY => 8,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 10.0,
            CLKOUT_PHASE_SHIFT => "NONE",
            DCM_AUTOCALIBRATION => FALSE,
            DCM_PERFORMANCE_MODE => "MAX_SPEED",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"F0F0",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>CLK0_BUFG,
                CLKIN=>CLK_IN,
                DADDR(6 downto 0)=>GND_BUS_7(6 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>dcm_rst,
                CLKDV=>open,
                CLKFX=>CLKFX_BUF,
                CLKFX180=>open,
                CLK0=>CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>dcm_locked,
                PSDONE=>open);                               
   
end BEHAVIORAL;


