#ChipScope Core Inserter Project File Version 3.0
#Thu Nov 29 21:27:15 EST 2007
Project.device.designInputFile=D\:\\telops\\Common_HDL\\DDR_Ctrl\\Active-HDL\\MIG_dataproc\\synthesis\\mig_dataproc_top.ngc
Project.device.designOutputFile=D\:\\telops\\Common_HDL\\DDR_Ctrl\\Active-HDL\\MIG_dataproc\\synthesis\\mig_dataproc_top.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=d\:\\telops\\Common_HDL\\DDR_Ctrl\\Active-HDL\\MIG_dataproc\\synthesis
Project.device.useSRL16=true
Project.filter.dimension=3
Project.filter<0>=
Project.filter<1>=*CLK*
Project.filter<2>=clk*
Project.icon.boundaryScanChain=0
Project.icon.disableBUFGInsertion=false
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=2
Project.unit<0>.clockChannel=CLK_DDR0
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd1
Project.unit<0>.dataChannel<100>=DDR ddr DDR_test DIN<59>
Project.unit<0>.dataChannel<101>=DDR ddr DDR_test DIN<58>
Project.unit<0>.dataChannel<102>=DDR ddr DDR_test DIN<57>
Project.unit<0>.dataChannel<103>=DDR ddr DDR_test DIN<56>
Project.unit<0>.dataChannel<104>=DDR ddr DDR_test DIN<55>
Project.unit<0>.dataChannel<105>=DDR ddr DDR_test DIN<54>
Project.unit<0>.dataChannel<106>=DDR ddr DDR_test DIN<53>
Project.unit<0>.dataChannel<107>=DDR ddr DDR_test DIN<52>
Project.unit<0>.dataChannel<108>=DDR ddr DDR_test DIN<51>
Project.unit<0>.dataChannel<109>=DDR ddr DDR_test DIN<50>
Project.unit<0>.dataChannel<10>=DDR ddr DDR_test mem_test_controller LST_ADR
Project.unit<0>.dataChannel<110>=DDR ddr DDR_test DIN<49>
Project.unit<0>.dataChannel<111>=DDR ddr DDR_test DIN<48>
Project.unit<0>.dataChannel<112>=DDR ddr DDR_test DIN<47>
Project.unit<0>.dataChannel<113>=DDR ddr DDR_test DIN<46>
Project.unit<0>.dataChannel<114>=DDR ddr DDR_test DIN<45>
Project.unit<0>.dataChannel<115>=DDR ddr DDR_test DIN<44>
Project.unit<0>.dataChannel<116>=DDR ddr DDR_test DIN<43>
Project.unit<0>.dataChannel<117>=DDR ddr DDR_test DIN<42>
Project.unit<0>.dataChannel<118>=DDR ddr DDR_test DIN<41>
Project.unit<0>.dataChannel<119>=DDR ddr DDR_test DIN<40>
Project.unit<0>.dataChannel<11>=DDR ddr DDR_test mem_test_controller NXT_ADR
Project.unit<0>.dataChannel<120>=DDR ddr DDR_test DIN<39>
Project.unit<0>.dataChannel<121>=DDR ddr DDR_test DIN<38>
Project.unit<0>.dataChannel<122>=DDR ddr DDR_test DIN<37>
Project.unit<0>.dataChannel<123>=DDR ddr DDR_test DIN<36>
Project.unit<0>.dataChannel<124>=DDR ddr DDR_test DIN<35>
Project.unit<0>.dataChannel<125>=DDR ddr DDR_test DIN<34>
Project.unit<0>.dataChannel<126>=DDR ddr DDR_test DIN<33>
Project.unit<0>.dataChannel<127>=DDR ddr DDR_test DIN<32>
Project.unit<0>.dataChannel<128>=DDR ddr DDR_test DIN<31>
Project.unit<0>.dataChannel<129>=DDR ddr DDR_test DIN<30>
Project.unit<0>.dataChannel<12>=DDR ddr DDR_test mem_test_controller NXT_DAT
Project.unit<0>.dataChannel<130>=DDR ddr DDR_test DIN<29>
Project.unit<0>.dataChannel<131>=DDR ddr DDR_test DIN<28>
Project.unit<0>.dataChannel<132>=DDR ddr DDR_test DIN<27>
Project.unit<0>.dataChannel<133>=DDR ddr DDR_test DIN<26>
Project.unit<0>.dataChannel<134>=DDR ddr DDR_test DIN<25>
Project.unit<0>.dataChannel<135>=DDR ddr DDR_test DIN<24>
Project.unit<0>.dataChannel<136>=DDR ddr DDR_test DIN<23>
Project.unit<0>.dataChannel<137>=DDR ddr DDR_test DIN<22>
Project.unit<0>.dataChannel<138>=DDR ddr DDR_test DIN<21>
Project.unit<0>.dataChannel<139>=DDR ddr DDR_test DIN<20>
Project.unit<0>.dataChannel<13>=DDR ddr DDR_test mem_test_controller RST_GEN
Project.unit<0>.dataChannel<140>=DDR ddr DDR_test DIN<19>
Project.unit<0>.dataChannel<141>=DDR ddr DDR_test DIN<18>
Project.unit<0>.dataChannel<142>=DDR ddr DDR_test DIN<17>
Project.unit<0>.dataChannel<143>=DDR ddr DDR_test DIN<16>
Project.unit<0>.dataChannel<144>=DDR ddr DDR_test DIN<15>
Project.unit<0>.dataChannel<145>=DDR ddr DDR_test DIN<14>
Project.unit<0>.dataChannel<146>=DDR ddr DDR_test DIN<13>
Project.unit<0>.dataChannel<147>=DDR ddr DDR_test DIN<12>
Project.unit<0>.dataChannel<148>=DDR ddr DDR_test DIN<11>
Project.unit<0>.dataChannel<149>=DDR ddr DDR_test DIN<10>
Project.unit<0>.dataChannel<14>=DDR ddr DDR_test mem_test_controller SINIT
Project.unit<0>.dataChannel<150>=DDR ddr DDR_test DIN<9>
Project.unit<0>.dataChannel<151>=DDR ddr DDR_test DIN<8>
Project.unit<0>.dataChannel<152>=DDR ddr DDR_test DIN<7>
Project.unit<0>.dataChannel<153>=DDR ddr DDR_test DIN<6>
Project.unit<0>.dataChannel<154>=DDR ddr DDR_test DIN<5>
Project.unit<0>.dataChannel<155>=DDR ddr DDR_test DIN<4>
Project.unit<0>.dataChannel<156>=DDR ddr DDR_test DIN<3>
Project.unit<0>.dataChannel<157>=DDR ddr DDR_test DIN<2>
Project.unit<0>.dataChannel<158>=DDR ddr DDR_test DIN<1>
Project.unit<0>.dataChannel<159>=DDR ddr DDR_test DIN<0>
Project.unit<0>.dataChannel<15>=DDR ddr DDR_controller CORE_INITDONE
Project.unit<0>.dataChannel<160>=DDR ddr DDR_test adr_generator ADR<27>
Project.unit<0>.dataChannel<161>=DDR ddr DDR_test adr_generator ADR<26>
Project.unit<0>.dataChannel<162>=DDR ddr DDR_test adr_generator ADR<25>
Project.unit<0>.dataChannel<163>=DDR ddr DDR_test adr_generator ADR<24>
Project.unit<0>.dataChannel<164>=DDR ddr DDR_test adr_generator ADR<23>
Project.unit<0>.dataChannel<165>=DDR ddr DDR_test adr_generator ADR<22>
Project.unit<0>.dataChannel<166>=DDR ddr DDR_test adr_generator ADR<21>
Project.unit<0>.dataChannel<167>=DDR ddr DDR_test adr_generator ADR<20>
Project.unit<0>.dataChannel<168>=DDR ddr DDR_test adr_generator ADR<19>
Project.unit<0>.dataChannel<169>=DDR ddr DDR_test adr_generator ADR<18>
Project.unit<0>.dataChannel<16>=DDR ddr DDR_test DOUT<71>
Project.unit<0>.dataChannel<170>=DDR ddr DDR_test adr_generator ADR<17>
Project.unit<0>.dataChannel<171>=DDR ddr DDR_test adr_generator ADR<16>
Project.unit<0>.dataChannel<172>=DDR ddr DDR_test adr_generator ADR<15>
Project.unit<0>.dataChannel<173>=DDR ddr DDR_test adr_generator ADR<14>
Project.unit<0>.dataChannel<174>=DDR ddr DDR_test adr_generator ADR<13>
Project.unit<0>.dataChannel<175>=DDR ddr DDR_test adr_generator ADR<12>
Project.unit<0>.dataChannel<176>=DDR ddr DDR_test adr_generator ADR<11>
Project.unit<0>.dataChannel<177>=DDR ddr DDR_test adr_generator ADR<10>
Project.unit<0>.dataChannel<178>=DDR ddr DDR_test adr_generator ADR<9>
Project.unit<0>.dataChannel<179>=DDR ddr DDR_test adr_generator ADR<8>
Project.unit<0>.dataChannel<17>=DDR ddr DDR_test DOUT<70>
Project.unit<0>.dataChannel<180>=DDR ddr DDR_test adr_generator ADR<7>
Project.unit<0>.dataChannel<181>=DDR ddr DDR_test adr_generator ADR<6>
Project.unit<0>.dataChannel<182>=DDR ddr DDR_test adr_generator ADR<5>
Project.unit<0>.dataChannel<183>=DDR ddr DDR_test adr_generator ADR<4>
Project.unit<0>.dataChannel<184>=DDR ddr DDR_test adr_generator ADR<3>
Project.unit<0>.dataChannel<185>=DDR ddr DDR_test adr_generator ADR<2>
Project.unit<0>.dataChannel<186>=DDR ddr DDR_test adr_generator ADR<1>
Project.unit<0>.dataChannel<187>=DDR ddr DDR_test adr_generator ADR<0>
Project.unit<0>.dataChannel<18>=DDR ddr DDR_test DOUT<69>
Project.unit<0>.dataChannel<19>=DDR ddr DDR_test DOUT<68>
Project.unit<0>.dataChannel<1>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd2
Project.unit<0>.dataChannel<20>=DDR ddr DDR_test DOUT<67>
Project.unit<0>.dataChannel<21>=DDR ddr DDR_test DOUT<66>
Project.unit<0>.dataChannel<22>=DDR ddr DDR_test DOUT<65>
Project.unit<0>.dataChannel<23>=DDR ddr DDR_test DOUT<64>
Project.unit<0>.dataChannel<24>=DDR ddr DDR_test DOUT<63>
Project.unit<0>.dataChannel<25>=DDR ddr DDR_test DOUT<62>
Project.unit<0>.dataChannel<26>=DDR ddr DDR_test DOUT<61>
Project.unit<0>.dataChannel<27>=DDR ddr DDR_test DOUT<60>
Project.unit<0>.dataChannel<28>=DDR ddr DDR_test DOUT<59>
Project.unit<0>.dataChannel<29>=DDR ddr DDR_test DOUT<58>
Project.unit<0>.dataChannel<2>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd3
Project.unit<0>.dataChannel<30>=DDR ddr DDR_test DOUT<57>
Project.unit<0>.dataChannel<31>=DDR ddr DDR_test DOUT<56>
Project.unit<0>.dataChannel<32>=DDR ddr DDR_test DOUT<55>
Project.unit<0>.dataChannel<33>=DDR ddr DDR_test DOUT<54>
Project.unit<0>.dataChannel<34>=DDR ddr DDR_test DOUT<53>
Project.unit<0>.dataChannel<35>=DDR ddr DDR_test DOUT<52>
Project.unit<0>.dataChannel<36>=DDR ddr DDR_test DOUT<51>
Project.unit<0>.dataChannel<37>=DDR ddr DDR_test DOUT<50>
Project.unit<0>.dataChannel<38>=DDR ddr DDR_test DOUT<49>
Project.unit<0>.dataChannel<39>=DDR ddr DDR_test DOUT<48>
Project.unit<0>.dataChannel<3>=DDR ddr DDR_test mem_test_controller DATA_VLD
Project.unit<0>.dataChannel<40>=DDR ddr DDR_test DOUT<47>
Project.unit<0>.dataChannel<41>=DDR ddr DDR_test DOUT<46>
Project.unit<0>.dataChannel<42>=DDR ddr DDR_test DOUT<45>
Project.unit<0>.dataChannel<43>=DDR ddr DDR_test DOUT<44>
Project.unit<0>.dataChannel<44>=DDR ddr DDR_test DOUT<43>
Project.unit<0>.dataChannel<45>=DDR ddr DDR_test DOUT<42>
Project.unit<0>.dataChannel<46>=DDR ddr DDR_test DOUT<41>
Project.unit<0>.dataChannel<47>=DDR ddr DDR_test DOUT<40>
Project.unit<0>.dataChannel<48>=DDR ddr DDR_test DOUT<39>
Project.unit<0>.dataChannel<49>=DDR ddr DDR_test DOUT<38>
Project.unit<0>.dataChannel<4>=DDR ddr DDR_test mem_test_controller DAT_EQ
Project.unit<0>.dataChannel<50>=DDR ddr DDR_test DOUT<37>
Project.unit<0>.dataChannel<51>=DDR ddr DDR_test DOUT<36>
Project.unit<0>.dataChannel<52>=DDR ddr DDR_test DOUT<35>
Project.unit<0>.dataChannel<53>=DDR ddr DDR_test DOUT<34>
Project.unit<0>.dataChannel<54>=DDR ddr DDR_test DOUT<33>
Project.unit<0>.dataChannel<55>=DDR ddr DDR_test DOUT<32>
Project.unit<0>.dataChannel<56>=DDR ddr DDR_test DOUT<31>
Project.unit<0>.dataChannel<57>=DDR ddr DDR_test DOUT<30>
Project.unit<0>.dataChannel<58>=DDR ddr DDR_test DOUT<29>
Project.unit<0>.dataChannel<59>=DDR ddr DDR_test DOUT<28>
Project.unit<0>.dataChannel<5>=DDR ddr DDR_test mem_test_controller DAT_INV
Project.unit<0>.dataChannel<60>=DDR ddr DDR_test DOUT<27>
Project.unit<0>.dataChannel<61>=DDR ddr DDR_test DOUT<26>
Project.unit<0>.dataChannel<62>=DDR ddr DDR_test DOUT<25>
Project.unit<0>.dataChannel<63>=DDR ddr DDR_test DOUT<24>
Project.unit<0>.dataChannel<64>=DDR ddr DDR_test DOUT<23>
Project.unit<0>.dataChannel<65>=DDR ddr DDR_test DOUT<22>
Project.unit<0>.dataChannel<66>=DDR ddr DDR_test DOUT<21>
Project.unit<0>.dataChannel<67>=DDR ddr DDR_test DOUT<20>
Project.unit<0>.dataChannel<68>=DDR ddr DDR_test DOUT<19>
Project.unit<0>.dataChannel<69>=DDR ddr DDR_test DOUT<18>
Project.unit<0>.dataChannel<6>=DDR ddr DDR_test mem_test_controller DAT_PEND
Project.unit<0>.dataChannel<70>=DDR ddr DDR_test DOUT<17>
Project.unit<0>.dataChannel<71>=DDR ddr DDR_test DOUT<16>
Project.unit<0>.dataChannel<72>=DDR ddr DDR_test DOUT<15>
Project.unit<0>.dataChannel<73>=DDR ddr DDR_test DOUT<14>
Project.unit<0>.dataChannel<74>=DDR ddr DDR_test DOUT<13>
Project.unit<0>.dataChannel<75>=DDR ddr DDR_test DOUT<12>
Project.unit<0>.dataChannel<76>=DDR ddr DDR_test DOUT<11>
Project.unit<0>.dataChannel<77>=DDR ddr DDR_test DOUT<10>
Project.unit<0>.dataChannel<78>=DDR ddr DDR_test DOUT<9>
Project.unit<0>.dataChannel<79>=DDR ddr DDR_test DOUT<8>
Project.unit<0>.dataChannel<7>=DDR ddr DDR_test mem_test_controller DDRT_STAT<0>
Project.unit<0>.dataChannel<80>=DDR ddr DDR_test DOUT<7>
Project.unit<0>.dataChannel<81>=DDR ddr DDR_test DOUT<6>
Project.unit<0>.dataChannel<82>=DDR ddr DDR_test DOUT<5>
Project.unit<0>.dataChannel<83>=DDR ddr DDR_test DOUT<4>
Project.unit<0>.dataChannel<84>=DDR ddr DDR_test DOUT<3>
Project.unit<0>.dataChannel<85>=DDR ddr DDR_test DOUT<2>
Project.unit<0>.dataChannel<86>=DDR ddr DDR_test DOUT<1>
Project.unit<0>.dataChannel<87>=DDR ddr DDR_test DOUT<0>
Project.unit<0>.dataChannel<88>=DDR ddr DDR_test DIN<71>
Project.unit<0>.dataChannel<89>=DDR ddr DDR_test DIN<70>
Project.unit<0>.dataChannel<8>=DDR ddr DDR_test mem_test_controller DDRT_STAT<1>
Project.unit<0>.dataChannel<90>=DDR ddr DDR_test DIN<69>
Project.unit<0>.dataChannel<91>=DDR ddr DDR_test DIN<68>
Project.unit<0>.dataChannel<92>=DDR ddr DDR_test DIN<67>
Project.unit<0>.dataChannel<93>=DDR ddr DDR_test DIN<66>
Project.unit<0>.dataChannel<94>=DDR ddr DDR_test DIN<65>
Project.unit<0>.dataChannel<95>=DDR ddr DDR_test DIN<64>
Project.unit<0>.dataChannel<96>=DDR ddr DDR_test DIN<63>
Project.unit<0>.dataChannel<97>=DDR ddr DDR_test DIN<62>
Project.unit<0>.dataChannel<98>=DDR ddr DDR_test DIN<61>
Project.unit<0>.dataChannel<99>=DDR ddr DDR_test DIN<60>
Project.unit<0>.dataChannel<9>=DDR ddr DDR_test mem_test_controller EN_TEST
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=188
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd1
Project.unit<0>.triggerChannel<0><100>=DDR ddr DDR_test DIN<59>
Project.unit<0>.triggerChannel<0><101>=DDR ddr DDR_test DIN<58>
Project.unit<0>.triggerChannel<0><102>=DDR ddr DDR_test DIN<57>
Project.unit<0>.triggerChannel<0><103>=DDR ddr DDR_test DIN<56>
Project.unit<0>.triggerChannel<0><104>=DDR ddr DDR_test DIN<55>
Project.unit<0>.triggerChannel<0><105>=DDR ddr DDR_test DIN<54>
Project.unit<0>.triggerChannel<0><106>=DDR ddr DDR_test DIN<53>
Project.unit<0>.triggerChannel<0><107>=DDR ddr DDR_test DIN<52>
Project.unit<0>.triggerChannel<0><108>=DDR ddr DDR_test DIN<51>
Project.unit<0>.triggerChannel<0><109>=DDR ddr DDR_test DIN<50>
Project.unit<0>.triggerChannel<0><10>=DDR ddr DDR_test mem_test_controller LST_ADR
Project.unit<0>.triggerChannel<0><110>=DDR ddr DDR_test DIN<49>
Project.unit<0>.triggerChannel<0><111>=DDR ddr DDR_test DIN<48>
Project.unit<0>.triggerChannel<0><112>=DDR ddr DDR_test DIN<47>
Project.unit<0>.triggerChannel<0><113>=DDR ddr DDR_test DIN<46>
Project.unit<0>.triggerChannel<0><114>=DDR ddr DDR_test DIN<45>
Project.unit<0>.triggerChannel<0><115>=DDR ddr DDR_test DIN<44>
Project.unit<0>.triggerChannel<0><116>=DDR ddr DDR_test DIN<43>
Project.unit<0>.triggerChannel<0><117>=DDR ddr DDR_test DIN<42>
Project.unit<0>.triggerChannel<0><118>=DDR ddr DDR_test DIN<41>
Project.unit<0>.triggerChannel<0><119>=DDR ddr DDR_test DIN<40>
Project.unit<0>.triggerChannel<0><11>=DDR ddr DDR_test mem_test_controller NXT_ADR
Project.unit<0>.triggerChannel<0><120>=DDR ddr DDR_test DIN<39>
Project.unit<0>.triggerChannel<0><121>=DDR ddr DDR_test DIN<38>
Project.unit<0>.triggerChannel<0><122>=DDR ddr DDR_test DIN<37>
Project.unit<0>.triggerChannel<0><123>=DDR ddr DDR_test DIN<36>
Project.unit<0>.triggerChannel<0><124>=DDR ddr DDR_test DIN<35>
Project.unit<0>.triggerChannel<0><125>=DDR ddr DDR_test DIN<34>
Project.unit<0>.triggerChannel<0><126>=DDR ddr DDR_test DIN<33>
Project.unit<0>.triggerChannel<0><127>=DDR ddr DDR_test DIN<32>
Project.unit<0>.triggerChannel<0><128>=DDR ddr DDR_test DIN<31>
Project.unit<0>.triggerChannel<0><129>=DDR ddr DDR_test DIN<30>
Project.unit<0>.triggerChannel<0><12>=DDR ddr DDR_test mem_test_controller NXT_DAT
Project.unit<0>.triggerChannel<0><130>=DDR ddr DDR_test DIN<29>
Project.unit<0>.triggerChannel<0><131>=DDR ddr DDR_test DIN<28>
Project.unit<0>.triggerChannel<0><132>=DDR ddr DDR_test DIN<27>
Project.unit<0>.triggerChannel<0><133>=DDR ddr DDR_test DIN<26>
Project.unit<0>.triggerChannel<0><134>=DDR ddr DDR_test DIN<25>
Project.unit<0>.triggerChannel<0><135>=DDR ddr DDR_test DIN<24>
Project.unit<0>.triggerChannel<0><136>=DDR ddr DDR_test DIN<23>
Project.unit<0>.triggerChannel<0><137>=DDR ddr DDR_test DIN<22>
Project.unit<0>.triggerChannel<0><138>=DDR ddr DDR_test DIN<21>
Project.unit<0>.triggerChannel<0><139>=DDR ddr DDR_test DIN<20>
Project.unit<0>.triggerChannel<0><13>=DDR ddr DDR_test mem_test_controller RST_GEN
Project.unit<0>.triggerChannel<0><140>=DDR ddr DDR_test DIN<19>
Project.unit<0>.triggerChannel<0><141>=DDR ddr DDR_test DIN<18>
Project.unit<0>.triggerChannel<0><142>=DDR ddr DDR_test DIN<17>
Project.unit<0>.triggerChannel<0><143>=DDR ddr DDR_test DIN<16>
Project.unit<0>.triggerChannel<0><144>=DDR ddr DDR_test DIN<15>
Project.unit<0>.triggerChannel<0><145>=DDR ddr DDR_test DIN<14>
Project.unit<0>.triggerChannel<0><146>=DDR ddr DDR_test DIN<13>
Project.unit<0>.triggerChannel<0><147>=DDR ddr DDR_test DIN<12>
Project.unit<0>.triggerChannel<0><148>=DDR ddr DDR_test DIN<11>
Project.unit<0>.triggerChannel<0><149>=DDR ddr DDR_test DIN<10>
Project.unit<0>.triggerChannel<0><14>=DDR ddr DDR_test mem_test_controller SINIT
Project.unit<0>.triggerChannel<0><150>=DDR ddr DDR_test DIN<9>
Project.unit<0>.triggerChannel<0><151>=DDR ddr DDR_test DIN<8>
Project.unit<0>.triggerChannel<0><152>=DDR ddr DDR_test DIN<7>
Project.unit<0>.triggerChannel<0><153>=DDR ddr DDR_test DIN<6>
Project.unit<0>.triggerChannel<0><154>=DDR ddr DDR_test DIN<5>
Project.unit<0>.triggerChannel<0><155>=DDR ddr DDR_test DIN<4>
Project.unit<0>.triggerChannel<0><156>=DDR ddr DDR_test DIN<3>
Project.unit<0>.triggerChannel<0><157>=DDR ddr DDR_test DIN<2>
Project.unit<0>.triggerChannel<0><158>=DDR ddr DDR_test DIN<1>
Project.unit<0>.triggerChannel<0><159>=DDR ddr DDR_test DIN<0>
Project.unit<0>.triggerChannel<0><15>=DDR ddr DDR_controller CORE_INITDONE
Project.unit<0>.triggerChannel<0><160>=DDR ddr DDR_test adr_generator ADR<27>
Project.unit<0>.triggerChannel<0><161>=DDR ddr DDR_test adr_generator ADR<26>
Project.unit<0>.triggerChannel<0><162>=DDR ddr DDR_test adr_generator ADR<25>
Project.unit<0>.triggerChannel<0><163>=DDR ddr DDR_test adr_generator ADR<24>
Project.unit<0>.triggerChannel<0><164>=DDR ddr DDR_test adr_generator ADR<23>
Project.unit<0>.triggerChannel<0><165>=DDR ddr DDR_test adr_generator ADR<22>
Project.unit<0>.triggerChannel<0><166>=DDR ddr DDR_test adr_generator ADR<21>
Project.unit<0>.triggerChannel<0><167>=DDR ddr DDR_test adr_generator ADR<20>
Project.unit<0>.triggerChannel<0><168>=DDR ddr DDR_test adr_generator ADR<19>
Project.unit<0>.triggerChannel<0><169>=DDR ddr DDR_test adr_generator ADR<18>
Project.unit<0>.triggerChannel<0><16>=DDR ddr DDR_test DOUT<71>
Project.unit<0>.triggerChannel<0><170>=DDR ddr DDR_test adr_generator ADR<17>
Project.unit<0>.triggerChannel<0><171>=DDR ddr DDR_test adr_generator ADR<16>
Project.unit<0>.triggerChannel<0><172>=DDR ddr DDR_test adr_generator ADR<15>
Project.unit<0>.triggerChannel<0><173>=DDR ddr DDR_test adr_generator ADR<14>
Project.unit<0>.triggerChannel<0><174>=DDR ddr DDR_test adr_generator ADR<13>
Project.unit<0>.triggerChannel<0><175>=DDR ddr DDR_test adr_generator ADR<12>
Project.unit<0>.triggerChannel<0><176>=DDR ddr DDR_test adr_generator ADR<11>
Project.unit<0>.triggerChannel<0><177>=DDR ddr DDR_test adr_generator ADR<10>
Project.unit<0>.triggerChannel<0><178>=DDR ddr DDR_test adr_generator ADR<9>
Project.unit<0>.triggerChannel<0><179>=DDR ddr DDR_test adr_generator ADR<8>
Project.unit<0>.triggerChannel<0><17>=DDR ddr DDR_test DOUT<70>
Project.unit<0>.triggerChannel<0><180>=DDR ddr DDR_test adr_generator ADR<7>
Project.unit<0>.triggerChannel<0><181>=DDR ddr DDR_test adr_generator ADR<6>
Project.unit<0>.triggerChannel<0><182>=DDR ddr DDR_test adr_generator ADR<5>
Project.unit<0>.triggerChannel<0><183>=DDR ddr DDR_test adr_generator ADR<4>
Project.unit<0>.triggerChannel<0><184>=DDR ddr DDR_test adr_generator ADR<3>
Project.unit<0>.triggerChannel<0><185>=DDR ddr DDR_test adr_generator ADR<2>
Project.unit<0>.triggerChannel<0><186>=DDR ddr DDR_test adr_generator ADR<1>
Project.unit<0>.triggerChannel<0><187>=DDR ddr DDR_test adr_generator ADR<0>
Project.unit<0>.triggerChannel<0><18>=DDR ddr DDR_test DOUT<69>
Project.unit<0>.triggerChannel<0><19>=DDR ddr DDR_test DOUT<68>
Project.unit<0>.triggerChannel<0><1>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd2
Project.unit<0>.triggerChannel<0><20>=DDR ddr DDR_test DOUT<67>
Project.unit<0>.triggerChannel<0><21>=DDR ddr DDR_test DOUT<66>
Project.unit<0>.triggerChannel<0><22>=DDR ddr DDR_test DOUT<65>
Project.unit<0>.triggerChannel<0><23>=DDR ddr DDR_test DOUT<64>
Project.unit<0>.triggerChannel<0><24>=DDR ddr DDR_test DOUT<63>
Project.unit<0>.triggerChannel<0><25>=DDR ddr DDR_test DOUT<62>
Project.unit<0>.triggerChannel<0><26>=DDR ddr DDR_test DOUT<61>
Project.unit<0>.triggerChannel<0><27>=DDR ddr DDR_test DOUT<60>
Project.unit<0>.triggerChannel<0><28>=DDR ddr DDR_test DOUT<59>
Project.unit<0>.triggerChannel<0><29>=DDR ddr DDR_test DOUT<58>
Project.unit<0>.triggerChannel<0><2>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd3
Project.unit<0>.triggerChannel<0><30>=DDR ddr DDR_test DOUT<57>
Project.unit<0>.triggerChannel<0><31>=DDR ddr DDR_test DOUT<56>
Project.unit<0>.triggerChannel<0><32>=DDR ddr DDR_test DOUT<55>
Project.unit<0>.triggerChannel<0><33>=DDR ddr DDR_test DOUT<54>
Project.unit<0>.triggerChannel<0><34>=DDR ddr DDR_test DOUT<53>
Project.unit<0>.triggerChannel<0><35>=DDR ddr DDR_test DOUT<52>
Project.unit<0>.triggerChannel<0><36>=DDR ddr DDR_test DOUT<51>
Project.unit<0>.triggerChannel<0><37>=DDR ddr DDR_test DOUT<50>
Project.unit<0>.triggerChannel<0><38>=DDR ddr DDR_test DOUT<49>
Project.unit<0>.triggerChannel<0><39>=DDR ddr DDR_test DOUT<48>
Project.unit<0>.triggerChannel<0><3>=DDR ddr DDR_test mem_test_controller DATA_VLD
Project.unit<0>.triggerChannel<0><40>=DDR ddr DDR_test DOUT<47>
Project.unit<0>.triggerChannel<0><41>=DDR ddr DDR_test DOUT<46>
Project.unit<0>.triggerChannel<0><42>=DDR ddr DDR_test DOUT<45>
Project.unit<0>.triggerChannel<0><43>=DDR ddr DDR_test DOUT<44>
Project.unit<0>.triggerChannel<0><44>=DDR ddr DDR_test DOUT<43>
Project.unit<0>.triggerChannel<0><45>=DDR ddr DDR_test DOUT<42>
Project.unit<0>.triggerChannel<0><46>=DDR ddr DDR_test DOUT<41>
Project.unit<0>.triggerChannel<0><47>=DDR ddr DDR_test DOUT<40>
Project.unit<0>.triggerChannel<0><48>=DDR ddr DDR_test DOUT<39>
Project.unit<0>.triggerChannel<0><49>=DDR ddr DDR_test DOUT<38>
Project.unit<0>.triggerChannel<0><4>=DDR ddr DDR_test mem_test_controller DAT_EQ
Project.unit<0>.triggerChannel<0><50>=DDR ddr DDR_test DOUT<37>
Project.unit<0>.triggerChannel<0><51>=DDR ddr DDR_test DOUT<36>
Project.unit<0>.triggerChannel<0><52>=DDR ddr DDR_test DOUT<35>
Project.unit<0>.triggerChannel<0><53>=DDR ddr DDR_test DOUT<34>
Project.unit<0>.triggerChannel<0><54>=DDR ddr DDR_test DOUT<33>
Project.unit<0>.triggerChannel<0><55>=DDR ddr DDR_test DOUT<32>
Project.unit<0>.triggerChannel<0><56>=DDR ddr DDR_test DOUT<31>
Project.unit<0>.triggerChannel<0><57>=DDR ddr DDR_test DOUT<30>
Project.unit<0>.triggerChannel<0><58>=DDR ddr DDR_test DOUT<29>
Project.unit<0>.triggerChannel<0><59>=DDR ddr DDR_test DOUT<28>
Project.unit<0>.triggerChannel<0><5>=DDR ddr DDR_test mem_test_controller DAT_INV
Project.unit<0>.triggerChannel<0><60>=DDR ddr DDR_test DOUT<27>
Project.unit<0>.triggerChannel<0><61>=DDR ddr DDR_test DOUT<26>
Project.unit<0>.triggerChannel<0><62>=DDR ddr DDR_test DOUT<25>
Project.unit<0>.triggerChannel<0><63>=DDR ddr DDR_test DOUT<24>
Project.unit<0>.triggerChannel<0><64>=DDR ddr DDR_test DOUT<23>
Project.unit<0>.triggerChannel<0><65>=DDR ddr DDR_test DOUT<22>
Project.unit<0>.triggerChannel<0><66>=DDR ddr DDR_test DOUT<21>
Project.unit<0>.triggerChannel<0><67>=DDR ddr DDR_test DOUT<20>
Project.unit<0>.triggerChannel<0><68>=DDR ddr DDR_test DOUT<19>
Project.unit<0>.triggerChannel<0><69>=DDR ddr DDR_test DOUT<18>
Project.unit<0>.triggerChannel<0><6>=DDR ddr DDR_test mem_test_controller DAT_PEND
Project.unit<0>.triggerChannel<0><70>=DDR ddr DDR_test DOUT<17>
Project.unit<0>.triggerChannel<0><71>=DDR ddr DDR_test DOUT<16>
Project.unit<0>.triggerChannel<0><72>=DDR ddr DDR_test DOUT<15>
Project.unit<0>.triggerChannel<0><73>=DDR ddr DDR_test DOUT<14>
Project.unit<0>.triggerChannel<0><74>=DDR ddr DDR_test DOUT<13>
Project.unit<0>.triggerChannel<0><75>=DDR ddr DDR_test DOUT<12>
Project.unit<0>.triggerChannel<0><76>=DDR ddr DDR_test DOUT<11>
Project.unit<0>.triggerChannel<0><77>=DDR ddr DDR_test DOUT<10>
Project.unit<0>.triggerChannel<0><78>=DDR ddr DDR_test DOUT<9>
Project.unit<0>.triggerChannel<0><79>=DDR ddr DDR_test DOUT<8>
Project.unit<0>.triggerChannel<0><7>=DDR ddr DDR_test mem_test_controller DDRT_STAT<0>
Project.unit<0>.triggerChannel<0><80>=DDR ddr DDR_test DOUT<7>
Project.unit<0>.triggerChannel<0><81>=DDR ddr DDR_test DOUT<6>
Project.unit<0>.triggerChannel<0><82>=DDR ddr DDR_test DOUT<5>
Project.unit<0>.triggerChannel<0><83>=DDR ddr DDR_test DOUT<4>
Project.unit<0>.triggerChannel<0><84>=DDR ddr DDR_test DOUT<3>
Project.unit<0>.triggerChannel<0><85>=DDR ddr DDR_test DOUT<2>
Project.unit<0>.triggerChannel<0><86>=DDR ddr DDR_test DOUT<1>
Project.unit<0>.triggerChannel<0><87>=DDR ddr DDR_test DOUT<0>
Project.unit<0>.triggerChannel<0><88>=DDR ddr DDR_test DIN<71>
Project.unit<0>.triggerChannel<0><89>=DDR ddr DDR_test DIN<70>
Project.unit<0>.triggerChannel<0><8>=DDR ddr DDR_test mem_test_controller DDRT_STAT<1>
Project.unit<0>.triggerChannel<0><90>=DDR ddr DDR_test DIN<69>
Project.unit<0>.triggerChannel<0><91>=DDR ddr DDR_test DIN<68>
Project.unit<0>.triggerChannel<0><92>=DDR ddr DDR_test DIN<67>
Project.unit<0>.triggerChannel<0><93>=DDR ddr DDR_test DIN<66>
Project.unit<0>.triggerChannel<0><94>=DDR ddr DDR_test DIN<65>
Project.unit<0>.triggerChannel<0><95>=DDR ddr DDR_test DIN<64>
Project.unit<0>.triggerChannel<0><96>=DDR ddr DDR_test DIN<63>
Project.unit<0>.triggerChannel<0><97>=DDR ddr DDR_test DIN<62>
Project.unit<0>.triggerChannel<0><98>=DDR ddr DDR_test DIN<61>
Project.unit<0>.triggerChannel<0><99>=DDR ddr DDR_test DIN<60>
Project.unit<0>.triggerChannel<0><9>=DDR ddr DDR_test mem_test_controller EN_TEST
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=0
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=188
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
Project.unit<1>.clockChannel=CLK_DDR0
Project.unit<1>.clockEdge=Rising
Project.unit<1>.dataChannel<0>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd1
Project.unit<1>.dataChannel<100>=DDR ddr DDR_test DIN<131>
Project.unit<1>.dataChannel<101>=DDR ddr DDR_test DIN<130>
Project.unit<1>.dataChannel<102>=DDR ddr DDR_test DIN<129>
Project.unit<1>.dataChannel<103>=DDR ddr DDR_test DIN<128>
Project.unit<1>.dataChannel<104>=DDR ddr DDR_test DIN<127>
Project.unit<1>.dataChannel<105>=DDR ddr DDR_test DIN<126>
Project.unit<1>.dataChannel<106>=DDR ddr DDR_test DIN<125>
Project.unit<1>.dataChannel<107>=DDR ddr DDR_test DIN<124>
Project.unit<1>.dataChannel<108>=DDR ddr DDR_test DIN<123>
Project.unit<1>.dataChannel<109>=DDR ddr DDR_test DIN<122>
Project.unit<1>.dataChannel<10>=DDR ddr DDR_test mem_test_controller LST_ADR
Project.unit<1>.dataChannel<110>=DDR ddr DDR_test DIN<121>
Project.unit<1>.dataChannel<111>=DDR ddr DDR_test DIN<120>
Project.unit<1>.dataChannel<112>=DDR ddr DDR_test DIN<119>
Project.unit<1>.dataChannel<113>=DDR ddr DDR_test DIN<118>
Project.unit<1>.dataChannel<114>=DDR ddr DDR_test DIN<117>
Project.unit<1>.dataChannel<115>=DDR ddr DDR_test DIN<116>
Project.unit<1>.dataChannel<116>=DDR ddr DDR_test DIN<115>
Project.unit<1>.dataChannel<117>=DDR ddr DDR_test DIN<114>
Project.unit<1>.dataChannel<118>=DDR ddr DDR_test DIN<113>
Project.unit<1>.dataChannel<119>=DDR ddr DDR_test DIN<112>
Project.unit<1>.dataChannel<11>=DDR ddr DDR_test mem_test_controller NXT_ADR
Project.unit<1>.dataChannel<120>=DDR ddr DDR_test DIN<111>
Project.unit<1>.dataChannel<121>=DDR ddr DDR_test DIN<110>
Project.unit<1>.dataChannel<122>=DDR ddr DDR_test DIN<109>
Project.unit<1>.dataChannel<123>=DDR ddr DDR_test DIN<108>
Project.unit<1>.dataChannel<124>=DDR ddr DDR_test DIN<107>
Project.unit<1>.dataChannel<125>=DDR ddr DDR_test DIN<106>
Project.unit<1>.dataChannel<126>=DDR ddr DDR_test DIN<105>
Project.unit<1>.dataChannel<127>=DDR ddr DDR_test DIN<104>
Project.unit<1>.dataChannel<128>=DDR ddr DDR_test DIN<103>
Project.unit<1>.dataChannel<129>=DDR ddr DDR_test DIN<102>
Project.unit<1>.dataChannel<12>=DDR ddr DDR_test mem_test_controller NXT_DAT
Project.unit<1>.dataChannel<130>=DDR ddr DDR_test DIN<101>
Project.unit<1>.dataChannel<131>=DDR ddr DDR_test DIN<100>
Project.unit<1>.dataChannel<132>=DDR ddr DDR_test DIN<99>
Project.unit<1>.dataChannel<133>=DDR ddr DDR_test DIN<98>
Project.unit<1>.dataChannel<134>=DDR ddr DDR_test DIN<97>
Project.unit<1>.dataChannel<135>=DDR ddr DDR_test DIN<96>
Project.unit<1>.dataChannel<136>=DDR ddr DDR_test DIN<95>
Project.unit<1>.dataChannel<137>=DDR ddr DDR_test DIN<94>
Project.unit<1>.dataChannel<138>=DDR ddr DDR_test DIN<93>
Project.unit<1>.dataChannel<139>=DDR ddr DDR_test DIN<92>
Project.unit<1>.dataChannel<13>=DDR ddr DDR_test mem_test_controller RST_GEN
Project.unit<1>.dataChannel<140>=DDR ddr DDR_test DIN<91>
Project.unit<1>.dataChannel<141>=DDR ddr DDR_test DIN<90>
Project.unit<1>.dataChannel<142>=DDR ddr DDR_test DIN<89>
Project.unit<1>.dataChannel<143>=DDR ddr DDR_test DIN<88>
Project.unit<1>.dataChannel<144>=DDR ddr DDR_test DIN<87>
Project.unit<1>.dataChannel<145>=DDR ddr DDR_test DIN<86>
Project.unit<1>.dataChannel<146>=DDR ddr DDR_test DIN<85>
Project.unit<1>.dataChannel<147>=DDR ddr DDR_test DIN<84>
Project.unit<1>.dataChannel<148>=DDR ddr DDR_test DIN<83>
Project.unit<1>.dataChannel<149>=DDR ddr DDR_test DIN<82>
Project.unit<1>.dataChannel<14>=DDR ddr DDR_test mem_test_controller SINIT
Project.unit<1>.dataChannel<150>=DDR ddr DDR_test DIN<81>
Project.unit<1>.dataChannel<151>=DDR ddr DDR_test DIN<80>
Project.unit<1>.dataChannel<152>=DDR ddr DDR_test DIN<79>
Project.unit<1>.dataChannel<153>=DDR ddr DDR_test DIN<78>
Project.unit<1>.dataChannel<154>=DDR ddr DDR_test DIN<77>
Project.unit<1>.dataChannel<155>=DDR ddr DDR_test DIN<76>
Project.unit<1>.dataChannel<156>=DDR ddr DDR_test DIN<75>
Project.unit<1>.dataChannel<157>=DDR ddr DDR_test DIN<74>
Project.unit<1>.dataChannel<158>=DDR ddr DDR_test DIN<73>
Project.unit<1>.dataChannel<159>=DDR ddr DDR_test DIN<72>
Project.unit<1>.dataChannel<15>=DDR ddr DDR_controller CORE_INITDONE
Project.unit<1>.dataChannel<160>=DDR ddr DDR_test adr_generator ADR<27>
Project.unit<1>.dataChannel<161>=DDR ddr DDR_test adr_generator ADR<26>
Project.unit<1>.dataChannel<162>=DDR ddr DDR_test adr_generator ADR<25>
Project.unit<1>.dataChannel<163>=DDR ddr DDR_test adr_generator ADR<24>
Project.unit<1>.dataChannel<164>=DDR ddr DDR_test adr_generator ADR<23>
Project.unit<1>.dataChannel<165>=DDR ddr DDR_test adr_generator ADR<22>
Project.unit<1>.dataChannel<166>=DDR ddr DDR_test adr_generator ADR<21>
Project.unit<1>.dataChannel<167>=DDR ddr DDR_test adr_generator ADR<20>
Project.unit<1>.dataChannel<168>=DDR ddr DDR_test adr_generator ADR<19>
Project.unit<1>.dataChannel<169>=DDR ddr DDR_test adr_generator ADR<18>
Project.unit<1>.dataChannel<16>=DDR ddr DDR_test DOUT<143>
Project.unit<1>.dataChannel<170>=DDR ddr DDR_test adr_generator ADR<17>
Project.unit<1>.dataChannel<171>=DDR ddr DDR_test adr_generator ADR<16>
Project.unit<1>.dataChannel<172>=DDR ddr DDR_test adr_generator ADR<15>
Project.unit<1>.dataChannel<173>=DDR ddr DDR_test adr_generator ADR<14>
Project.unit<1>.dataChannel<174>=DDR ddr DDR_test adr_generator ADR<13>
Project.unit<1>.dataChannel<175>=DDR ddr DDR_test adr_generator ADR<12>
Project.unit<1>.dataChannel<176>=DDR ddr DDR_test adr_generator ADR<11>
Project.unit<1>.dataChannel<177>=DDR ddr DDR_test adr_generator ADR<10>
Project.unit<1>.dataChannel<178>=DDR ddr DDR_test adr_generator ADR<9>
Project.unit<1>.dataChannel<179>=DDR ddr DDR_test adr_generator ADR<8>
Project.unit<1>.dataChannel<17>=DDR ddr DDR_test DOUT<142>
Project.unit<1>.dataChannel<180>=DDR ddr DDR_test adr_generator ADR<7>
Project.unit<1>.dataChannel<181>=DDR ddr DDR_test adr_generator ADR<6>
Project.unit<1>.dataChannel<182>=DDR ddr DDR_test adr_generator ADR<5>
Project.unit<1>.dataChannel<183>=DDR ddr DDR_test adr_generator ADR<4>
Project.unit<1>.dataChannel<184>=DDR ddr DDR_test adr_generator ADR<3>
Project.unit<1>.dataChannel<185>=DDR ddr DDR_test adr_generator ADR<2>
Project.unit<1>.dataChannel<186>=DDR ddr DDR_test adr_generator ADR<1>
Project.unit<1>.dataChannel<187>=DDR ddr DDR_test adr_generator ADR<0>
Project.unit<1>.dataChannel<18>=DDR ddr DDR_test DOUT<141>
Project.unit<1>.dataChannel<19>=DDR ddr DDR_test DOUT<140>
Project.unit<1>.dataChannel<1>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd2
Project.unit<1>.dataChannel<20>=DDR ddr DDR_test DOUT<139>
Project.unit<1>.dataChannel<21>=DDR ddr DDR_test DOUT<138>
Project.unit<1>.dataChannel<22>=DDR ddr DDR_test DOUT<137>
Project.unit<1>.dataChannel<23>=DDR ddr DDR_test DOUT<136>
Project.unit<1>.dataChannel<24>=DDR ddr DDR_test DOUT<135>
Project.unit<1>.dataChannel<25>=DDR ddr DDR_test DOUT<134>
Project.unit<1>.dataChannel<26>=DDR ddr DDR_test DOUT<133>
Project.unit<1>.dataChannel<27>=DDR ddr DDR_test DOUT<132>
Project.unit<1>.dataChannel<28>=DDR ddr DDR_test DOUT<131>
Project.unit<1>.dataChannel<29>=DDR ddr DDR_test DOUT<130>
Project.unit<1>.dataChannel<2>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd3
Project.unit<1>.dataChannel<30>=DDR ddr DDR_test DOUT<129>
Project.unit<1>.dataChannel<31>=DDR ddr DDR_test DOUT<128>
Project.unit<1>.dataChannel<32>=DDR ddr DDR_test DOUT<127>
Project.unit<1>.dataChannel<33>=DDR ddr DDR_test DOUT<126>
Project.unit<1>.dataChannel<34>=DDR ddr DDR_test DOUT<125>
Project.unit<1>.dataChannel<35>=DDR ddr DDR_test DOUT<124>
Project.unit<1>.dataChannel<36>=DDR ddr DDR_test DOUT<123>
Project.unit<1>.dataChannel<37>=DDR ddr DDR_test DOUT<122>
Project.unit<1>.dataChannel<38>=DDR ddr DDR_test DOUT<121>
Project.unit<1>.dataChannel<39>=DDR ddr DDR_test DOUT<120>
Project.unit<1>.dataChannel<3>=DDR ddr DDR_test mem_test_controller DATA_VLD
Project.unit<1>.dataChannel<40>=DDR ddr DDR_test DOUT<119>
Project.unit<1>.dataChannel<41>=DDR ddr DDR_test DOUT<118>
Project.unit<1>.dataChannel<42>=DDR ddr DDR_test DOUT<117>
Project.unit<1>.dataChannel<43>=DDR ddr DDR_test DOUT<116>
Project.unit<1>.dataChannel<44>=DDR ddr DDR_test DOUT<115>
Project.unit<1>.dataChannel<45>=DDR ddr DDR_test DOUT<114>
Project.unit<1>.dataChannel<46>=DDR ddr DDR_test DOUT<113>
Project.unit<1>.dataChannel<47>=DDR ddr DDR_test DOUT<112>
Project.unit<1>.dataChannel<48>=DDR ddr DDR_test DOUT<111>
Project.unit<1>.dataChannel<49>=DDR ddr DDR_test DOUT<110>
Project.unit<1>.dataChannel<4>=DDR ddr DDR_test mem_test_controller DAT_EQ
Project.unit<1>.dataChannel<50>=DDR ddr DDR_test DOUT<109>
Project.unit<1>.dataChannel<51>=DDR ddr DDR_test DOUT<108>
Project.unit<1>.dataChannel<52>=DDR ddr DDR_test DOUT<107>
Project.unit<1>.dataChannel<53>=DDR ddr DDR_test DOUT<106>
Project.unit<1>.dataChannel<54>=DDR ddr DDR_test DOUT<105>
Project.unit<1>.dataChannel<55>=DDR ddr DDR_test DOUT<104>
Project.unit<1>.dataChannel<56>=DDR ddr DDR_test DOUT<103>
Project.unit<1>.dataChannel<57>=DDR ddr DDR_test DOUT<102>
Project.unit<1>.dataChannel<58>=DDR ddr DDR_test DOUT<101>
Project.unit<1>.dataChannel<59>=DDR ddr DDR_test DOUT<100>
Project.unit<1>.dataChannel<5>=DDR ddr DDR_test mem_test_controller DAT_INV
Project.unit<1>.dataChannel<60>=DDR ddr DDR_test DOUT<99>
Project.unit<1>.dataChannel<61>=DDR ddr DDR_test DOUT<98>
Project.unit<1>.dataChannel<62>=DDR ddr DDR_test DOUT<97>
Project.unit<1>.dataChannel<63>=DDR ddr DDR_test DOUT<96>
Project.unit<1>.dataChannel<64>=DDR ddr DDR_test DOUT<95>
Project.unit<1>.dataChannel<65>=DDR ddr DDR_test DOUT<94>
Project.unit<1>.dataChannel<66>=DDR ddr DDR_test DOUT<93>
Project.unit<1>.dataChannel<67>=DDR ddr DDR_test DOUT<92>
Project.unit<1>.dataChannel<68>=DDR ddr DDR_test DOUT<91>
Project.unit<1>.dataChannel<69>=DDR ddr DDR_test DOUT<90>
Project.unit<1>.dataChannel<6>=DDR ddr DDR_test mem_test_controller DAT_PEND
Project.unit<1>.dataChannel<70>=DDR ddr DDR_test DOUT<89>
Project.unit<1>.dataChannel<71>=DDR ddr DDR_test DOUT<88>
Project.unit<1>.dataChannel<72>=DDR ddr DDR_test DOUT<87>
Project.unit<1>.dataChannel<73>=DDR ddr DDR_test DOUT<86>
Project.unit<1>.dataChannel<74>=DDR ddr DDR_test DOUT<85>
Project.unit<1>.dataChannel<75>=DDR ddr DDR_test DOUT<84>
Project.unit<1>.dataChannel<76>=DDR ddr DDR_test DOUT<83>
Project.unit<1>.dataChannel<77>=DDR ddr DDR_test DOUT<82>
Project.unit<1>.dataChannel<78>=DDR ddr DDR_test DOUT<81>
Project.unit<1>.dataChannel<79>=DDR ddr DDR_test DOUT<80>
Project.unit<1>.dataChannel<7>=DDR ddr DDR_test mem_test_controller DDRT_STAT<0>
Project.unit<1>.dataChannel<80>=DDR ddr DDR_test DOUT<79>
Project.unit<1>.dataChannel<81>=DDR ddr DDR_test DOUT<78>
Project.unit<1>.dataChannel<82>=DDR ddr DDR_test DOUT<77>
Project.unit<1>.dataChannel<83>=DDR ddr DDR_test DOUT<76>
Project.unit<1>.dataChannel<84>=DDR ddr DDR_test DOUT<75>
Project.unit<1>.dataChannel<85>=DDR ddr DDR_test DOUT<74>
Project.unit<1>.dataChannel<86>=DDR ddr DDR_test DOUT<73>
Project.unit<1>.dataChannel<87>=DDR ddr DDR_test DOUT<72>
Project.unit<1>.dataChannel<88>=DDR ddr DDR_test DIN<143>
Project.unit<1>.dataChannel<89>=DDR ddr DDR_test DIN<142>
Project.unit<1>.dataChannel<8>=DDR ddr DDR_test mem_test_controller DDRT_STAT<1>
Project.unit<1>.dataChannel<90>=DDR ddr DDR_test DIN<141>
Project.unit<1>.dataChannel<91>=DDR ddr DDR_test DIN<140>
Project.unit<1>.dataChannel<92>=DDR ddr DDR_test DIN<139>
Project.unit<1>.dataChannel<93>=DDR ddr DDR_test DIN<138>
Project.unit<1>.dataChannel<94>=DDR ddr DDR_test DIN<137>
Project.unit<1>.dataChannel<95>=DDR ddr DDR_test DIN<136>
Project.unit<1>.dataChannel<96>=DDR ddr DDR_test DIN<135>
Project.unit<1>.dataChannel<97>=DDR ddr DDR_test DIN<134>
Project.unit<1>.dataChannel<98>=DDR ddr DDR_test DIN<133>
Project.unit<1>.dataChannel<99>=DDR ddr DDR_test DIN<132>
Project.unit<1>.dataChannel<9>=DDR ddr DDR_test mem_test_controller EN_TEST
Project.unit<1>.dataDepth=1024
Project.unit<1>.dataEqualsTrigger=true
Project.unit<1>.dataPortWidth=188
Project.unit<1>.enableGaps=false
Project.unit<1>.enableStorageQualification=true
Project.unit<1>.enableTimestamps=false
Project.unit<1>.timestampDepth=0
Project.unit<1>.timestampWidth=0
Project.unit<1>.triggerChannel<0><0>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd1
Project.unit<1>.triggerChannel<0><100>=DDR ddr DDR_test DIN<131>
Project.unit<1>.triggerChannel<0><101>=DDR ddr DDR_test DIN<130>
Project.unit<1>.triggerChannel<0><102>=DDR ddr DDR_test DIN<129>
Project.unit<1>.triggerChannel<0><103>=DDR ddr DDR_test DIN<128>
Project.unit<1>.triggerChannel<0><104>=DDR ddr DDR_test DIN<127>
Project.unit<1>.triggerChannel<0><105>=DDR ddr DDR_test DIN<126>
Project.unit<1>.triggerChannel<0><106>=DDR ddr DDR_test DIN<125>
Project.unit<1>.triggerChannel<0><107>=DDR ddr DDR_test DIN<124>
Project.unit<1>.triggerChannel<0><108>=DDR ddr DDR_test DIN<123>
Project.unit<1>.triggerChannel<0><109>=DDR ddr DDR_test DIN<122>
Project.unit<1>.triggerChannel<0><10>=DDR ddr DDR_test mem_test_controller LST_ADR
Project.unit<1>.triggerChannel<0><110>=DDR ddr DDR_test DIN<121>
Project.unit<1>.triggerChannel<0><111>=DDR ddr DDR_test DIN<120>
Project.unit<1>.triggerChannel<0><112>=DDR ddr DDR_test DIN<119>
Project.unit<1>.triggerChannel<0><113>=DDR ddr DDR_test DIN<118>
Project.unit<1>.triggerChannel<0><114>=DDR ddr DDR_test DIN<117>
Project.unit<1>.triggerChannel<0><115>=DDR ddr DDR_test DIN<116>
Project.unit<1>.triggerChannel<0><116>=DDR ddr DDR_test DIN<115>
Project.unit<1>.triggerChannel<0><117>=DDR ddr DDR_test DIN<114>
Project.unit<1>.triggerChannel<0><118>=DDR ddr DDR_test DIN<113>
Project.unit<1>.triggerChannel<0><119>=DDR ddr DDR_test DIN<112>
Project.unit<1>.triggerChannel<0><11>=DDR ddr DDR_test mem_test_controller NXT_ADR
Project.unit<1>.triggerChannel<0><120>=DDR ddr DDR_test DIN<111>
Project.unit<1>.triggerChannel<0><121>=DDR ddr DDR_test DIN<110>
Project.unit<1>.triggerChannel<0><122>=DDR ddr DDR_test DIN<109>
Project.unit<1>.triggerChannel<0><123>=DDR ddr DDR_test DIN<108>
Project.unit<1>.triggerChannel<0><124>=DDR ddr DDR_test DIN<107>
Project.unit<1>.triggerChannel<0><125>=DDR ddr DDR_test DIN<106>
Project.unit<1>.triggerChannel<0><126>=DDR ddr DDR_test DIN<105>
Project.unit<1>.triggerChannel<0><127>=DDR ddr DDR_test DIN<104>
Project.unit<1>.triggerChannel<0><128>=DDR ddr DDR_test DIN<103>
Project.unit<1>.triggerChannel<0><129>=DDR ddr DDR_test DIN<102>
Project.unit<1>.triggerChannel<0><12>=DDR ddr DDR_test mem_test_controller NXT_DAT
Project.unit<1>.triggerChannel<0><130>=DDR ddr DDR_test DIN<101>
Project.unit<1>.triggerChannel<0><131>=DDR ddr DDR_test DIN<100>
Project.unit<1>.triggerChannel<0><132>=DDR ddr DDR_test DIN<99>
Project.unit<1>.triggerChannel<0><133>=DDR ddr DDR_test DIN<98>
Project.unit<1>.triggerChannel<0><134>=DDR ddr DDR_test DIN<97>
Project.unit<1>.triggerChannel<0><135>=DDR ddr DDR_test DIN<96>
Project.unit<1>.triggerChannel<0><136>=DDR ddr DDR_test DIN<95>
Project.unit<1>.triggerChannel<0><137>=DDR ddr DDR_test DIN<94>
Project.unit<1>.triggerChannel<0><138>=DDR ddr DDR_test DIN<93>
Project.unit<1>.triggerChannel<0><139>=DDR ddr DDR_test DIN<92>
Project.unit<1>.triggerChannel<0><13>=DDR ddr DDR_test mem_test_controller RST_GEN
Project.unit<1>.triggerChannel<0><140>=DDR ddr DDR_test DIN<91>
Project.unit<1>.triggerChannel<0><141>=DDR ddr DDR_test DIN<90>
Project.unit<1>.triggerChannel<0><142>=DDR ddr DDR_test DIN<89>
Project.unit<1>.triggerChannel<0><143>=DDR ddr DDR_test DIN<88>
Project.unit<1>.triggerChannel<0><144>=DDR ddr DDR_test DIN<87>
Project.unit<1>.triggerChannel<0><145>=DDR ddr DDR_test DIN<86>
Project.unit<1>.triggerChannel<0><146>=DDR ddr DDR_test DIN<85>
Project.unit<1>.triggerChannel<0><147>=DDR ddr DDR_test DIN<84>
Project.unit<1>.triggerChannel<0><148>=DDR ddr DDR_test DIN<83>
Project.unit<1>.triggerChannel<0><149>=DDR ddr DDR_test DIN<82>
Project.unit<1>.triggerChannel<0><14>=DDR ddr DDR_test mem_test_controller SINIT
Project.unit<1>.triggerChannel<0><150>=DDR ddr DDR_test DIN<81>
Project.unit<1>.triggerChannel<0><151>=DDR ddr DDR_test DIN<80>
Project.unit<1>.triggerChannel<0><152>=DDR ddr DDR_test DIN<79>
Project.unit<1>.triggerChannel<0><153>=DDR ddr DDR_test DIN<78>
Project.unit<1>.triggerChannel<0><154>=DDR ddr DDR_test DIN<77>
Project.unit<1>.triggerChannel<0><155>=DDR ddr DDR_test DIN<76>
Project.unit<1>.triggerChannel<0><156>=DDR ddr DDR_test DIN<75>
Project.unit<1>.triggerChannel<0><157>=DDR ddr DDR_test DIN<74>
Project.unit<1>.triggerChannel<0><158>=DDR ddr DDR_test DIN<73>
Project.unit<1>.triggerChannel<0><159>=DDR ddr DDR_test DIN<72>
Project.unit<1>.triggerChannel<0><15>=DDR ddr DDR_controller CORE_INITDONE
Project.unit<1>.triggerChannel<0><160>=DDR ddr DDR_test adr_generator ADR<27>
Project.unit<1>.triggerChannel<0><161>=DDR ddr DDR_test adr_generator ADR<26>
Project.unit<1>.triggerChannel<0><162>=DDR ddr DDR_test adr_generator ADR<25>
Project.unit<1>.triggerChannel<0><163>=DDR ddr DDR_test adr_generator ADR<24>
Project.unit<1>.triggerChannel<0><164>=DDR ddr DDR_test adr_generator ADR<23>
Project.unit<1>.triggerChannel<0><165>=DDR ddr DDR_test adr_generator ADR<22>
Project.unit<1>.triggerChannel<0><166>=DDR ddr DDR_test adr_generator ADR<21>
Project.unit<1>.triggerChannel<0><167>=DDR ddr DDR_test adr_generator ADR<20>
Project.unit<1>.triggerChannel<0><168>=DDR ddr DDR_test adr_generator ADR<19>
Project.unit<1>.triggerChannel<0><169>=DDR ddr DDR_test adr_generator ADR<18>
Project.unit<1>.triggerChannel<0><16>=DDR ddr DDR_test DOUT<143>
Project.unit<1>.triggerChannel<0><170>=DDR ddr DDR_test adr_generator ADR<17>
Project.unit<1>.triggerChannel<0><171>=DDR ddr DDR_test adr_generator ADR<16>
Project.unit<1>.triggerChannel<0><172>=DDR ddr DDR_test adr_generator ADR<15>
Project.unit<1>.triggerChannel<0><173>=DDR ddr DDR_test adr_generator ADR<14>
Project.unit<1>.triggerChannel<0><174>=DDR ddr DDR_test adr_generator ADR<13>
Project.unit<1>.triggerChannel<0><175>=DDR ddr DDR_test adr_generator ADR<12>
Project.unit<1>.triggerChannel<0><176>=DDR ddr DDR_test adr_generator ADR<11>
Project.unit<1>.triggerChannel<0><177>=DDR ddr DDR_test adr_generator ADR<10>
Project.unit<1>.triggerChannel<0><178>=DDR ddr DDR_test adr_generator ADR<9>
Project.unit<1>.triggerChannel<0><179>=DDR ddr DDR_test adr_generator ADR<8>
Project.unit<1>.triggerChannel<0><17>=DDR ddr DDR_test DOUT<142>
Project.unit<1>.triggerChannel<0><180>=DDR ddr DDR_test adr_generator ADR<7>
Project.unit<1>.triggerChannel<0><181>=DDR ddr DDR_test adr_generator ADR<6>
Project.unit<1>.triggerChannel<0><182>=DDR ddr DDR_test adr_generator ADR<5>
Project.unit<1>.triggerChannel<0><183>=DDR ddr DDR_test adr_generator ADR<4>
Project.unit<1>.triggerChannel<0><184>=DDR ddr DDR_test adr_generator ADR<3>
Project.unit<1>.triggerChannel<0><185>=DDR ddr DDR_test adr_generator ADR<2>
Project.unit<1>.triggerChannel<0><186>=DDR ddr DDR_test adr_generator ADR<1>
Project.unit<1>.triggerChannel<0><187>=DDR ddr DDR_test adr_generator ADR<0>
Project.unit<1>.triggerChannel<0><18>=DDR ddr DDR_test DOUT<141>
Project.unit<1>.triggerChannel<0><19>=DDR ddr DDR_test DOUT<140>
Project.unit<1>.triggerChannel<0><1>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd2
Project.unit<1>.triggerChannel<0><20>=DDR ddr DDR_test DOUT<139>
Project.unit<1>.triggerChannel<0><21>=DDR ddr DDR_test DOUT<138>
Project.unit<1>.triggerChannel<0><22>=DDR ddr DDR_test DOUT<137>
Project.unit<1>.triggerChannel<0><23>=DDR ddr DDR_test DOUT<136>
Project.unit<1>.triggerChannel<0><24>=DDR ddr DDR_test DOUT<135>
Project.unit<1>.triggerChannel<0><25>=DDR ddr DDR_test DOUT<134>
Project.unit<1>.triggerChannel<0><26>=DDR ddr DDR_test DOUT<133>
Project.unit<1>.triggerChannel<0><27>=DDR ddr DDR_test DOUT<132>
Project.unit<1>.triggerChannel<0><28>=DDR ddr DDR_test DOUT<131>
Project.unit<1>.triggerChannel<0><29>=DDR ddr DDR_test DOUT<130>
Project.unit<1>.triggerChannel<0><2>=DDR ddr DDR_test mem_test_controller ddr_test_sm_FFd3
Project.unit<1>.triggerChannel<0><30>=DDR ddr DDR_test DOUT<129>
Project.unit<1>.triggerChannel<0><31>=DDR ddr DDR_test DOUT<128>
Project.unit<1>.triggerChannel<0><32>=DDR ddr DDR_test DOUT<127>
Project.unit<1>.triggerChannel<0><33>=DDR ddr DDR_test DOUT<126>
Project.unit<1>.triggerChannel<0><34>=DDR ddr DDR_test DOUT<125>
Project.unit<1>.triggerChannel<0><35>=DDR ddr DDR_test DOUT<124>
Project.unit<1>.triggerChannel<0><36>=DDR ddr DDR_test DOUT<123>
Project.unit<1>.triggerChannel<0><37>=DDR ddr DDR_test DOUT<122>
Project.unit<1>.triggerChannel<0><38>=DDR ddr DDR_test DOUT<121>
Project.unit<1>.triggerChannel<0><39>=DDR ddr DDR_test DOUT<120>
Project.unit<1>.triggerChannel<0><3>=DDR ddr DDR_test mem_test_controller DATA_VLD
Project.unit<1>.triggerChannel<0><40>=DDR ddr DDR_test DOUT<119>
Project.unit<1>.triggerChannel<0><41>=DDR ddr DDR_test DOUT<118>
Project.unit<1>.triggerChannel<0><42>=DDR ddr DDR_test DOUT<117>
Project.unit<1>.triggerChannel<0><43>=DDR ddr DDR_test DOUT<116>
Project.unit<1>.triggerChannel<0><44>=DDR ddr DDR_test DOUT<115>
Project.unit<1>.triggerChannel<0><45>=DDR ddr DDR_test DOUT<114>
Project.unit<1>.triggerChannel<0><46>=DDR ddr DDR_test DOUT<113>
Project.unit<1>.triggerChannel<0><47>=DDR ddr DDR_test DOUT<112>
Project.unit<1>.triggerChannel<0><48>=DDR ddr DDR_test DOUT<111>
Project.unit<1>.triggerChannel<0><49>=DDR ddr DDR_test DOUT<110>
Project.unit<1>.triggerChannel<0><4>=DDR ddr DDR_test mem_test_controller DAT_EQ
Project.unit<1>.triggerChannel<0><50>=DDR ddr DDR_test DOUT<109>
Project.unit<1>.triggerChannel<0><51>=DDR ddr DDR_test DOUT<108>
Project.unit<1>.triggerChannel<0><52>=DDR ddr DDR_test DOUT<107>
Project.unit<1>.triggerChannel<0><53>=DDR ddr DDR_test DOUT<106>
Project.unit<1>.triggerChannel<0><54>=DDR ddr DDR_test DOUT<105>
Project.unit<1>.triggerChannel<0><55>=DDR ddr DDR_test DOUT<104>
Project.unit<1>.triggerChannel<0><56>=DDR ddr DDR_test DOUT<103>
Project.unit<1>.triggerChannel<0><57>=DDR ddr DDR_test DOUT<102>
Project.unit<1>.triggerChannel<0><58>=DDR ddr DDR_test DOUT<101>
Project.unit<1>.triggerChannel<0><59>=DDR ddr DDR_test DOUT<100>
Project.unit<1>.triggerChannel<0><5>=DDR ddr DDR_test mem_test_controller DAT_INV
Project.unit<1>.triggerChannel<0><60>=DDR ddr DDR_test DOUT<99>
Project.unit<1>.triggerChannel<0><61>=DDR ddr DDR_test DOUT<98>
Project.unit<1>.triggerChannel<0><62>=DDR ddr DDR_test DOUT<97>
Project.unit<1>.triggerChannel<0><63>=DDR ddr DDR_test DOUT<96>
Project.unit<1>.triggerChannel<0><64>=DDR ddr DDR_test DOUT<95>
Project.unit<1>.triggerChannel<0><65>=DDR ddr DDR_test DOUT<94>
Project.unit<1>.triggerChannel<0><66>=DDR ddr DDR_test DOUT<93>
Project.unit<1>.triggerChannel<0><67>=DDR ddr DDR_test DOUT<92>
Project.unit<1>.triggerChannel<0><68>=DDR ddr DDR_test DOUT<91>
Project.unit<1>.triggerChannel<0><69>=DDR ddr DDR_test DOUT<90>
Project.unit<1>.triggerChannel<0><6>=DDR ddr DDR_test mem_test_controller DAT_PEND
Project.unit<1>.triggerChannel<0><70>=DDR ddr DDR_test DOUT<89>
Project.unit<1>.triggerChannel<0><71>=DDR ddr DDR_test DOUT<88>
Project.unit<1>.triggerChannel<0><72>=DDR ddr DDR_test DOUT<87>
Project.unit<1>.triggerChannel<0><73>=DDR ddr DDR_test DOUT<86>
Project.unit<1>.triggerChannel<0><74>=DDR ddr DDR_test DOUT<85>
Project.unit<1>.triggerChannel<0><75>=DDR ddr DDR_test DOUT<84>
Project.unit<1>.triggerChannel<0><76>=DDR ddr DDR_test DOUT<83>
Project.unit<1>.triggerChannel<0><77>=DDR ddr DDR_test DOUT<82>
Project.unit<1>.triggerChannel<0><78>=DDR ddr DDR_test DOUT<81>
Project.unit<1>.triggerChannel<0><79>=DDR ddr DDR_test DOUT<80>
Project.unit<1>.triggerChannel<0><7>=DDR ddr DDR_test mem_test_controller DDRT_STAT<0>
Project.unit<1>.triggerChannel<0><80>=DDR ddr DDR_test DOUT<79>
Project.unit<1>.triggerChannel<0><81>=DDR ddr DDR_test DOUT<78>
Project.unit<1>.triggerChannel<0><82>=DDR ddr DDR_test DOUT<77>
Project.unit<1>.triggerChannel<0><83>=DDR ddr DDR_test DOUT<76>
Project.unit<1>.triggerChannel<0><84>=DDR ddr DDR_test DOUT<75>
Project.unit<1>.triggerChannel<0><85>=DDR ddr DDR_test DOUT<74>
Project.unit<1>.triggerChannel<0><86>=DDR ddr DDR_test DOUT<73>
Project.unit<1>.triggerChannel<0><87>=DDR ddr DDR_test DOUT<72>
Project.unit<1>.triggerChannel<0><88>=DDR ddr DDR_test DIN<143>
Project.unit<1>.triggerChannel<0><89>=DDR ddr DDR_test DIN<142>
Project.unit<1>.triggerChannel<0><8>=DDR ddr DDR_test mem_test_controller DDRT_STAT<1>
Project.unit<1>.triggerChannel<0><90>=DDR ddr DDR_test DIN<141>
Project.unit<1>.triggerChannel<0><91>=DDR ddr DDR_test DIN<140>
Project.unit<1>.triggerChannel<0><92>=DDR ddr DDR_test DIN<139>
Project.unit<1>.triggerChannel<0><93>=DDR ddr DDR_test DIN<138>
Project.unit<1>.triggerChannel<0><94>=DDR ddr DDR_test DIN<137>
Project.unit<1>.triggerChannel<0><95>=DDR ddr DDR_test DIN<136>
Project.unit<1>.triggerChannel<0><96>=DDR ddr DDR_test DIN<135>
Project.unit<1>.triggerChannel<0><97>=DDR ddr DDR_test DIN<134>
Project.unit<1>.triggerChannel<0><98>=DDR ddr DDR_test DIN<133>
Project.unit<1>.triggerChannel<0><99>=DDR ddr DDR_test DIN<132>
Project.unit<1>.triggerChannel<0><9>=DDR ddr DDR_test mem_test_controller EN_TEST
Project.unit<1>.triggerConditionCountWidth=0
Project.unit<1>.triggerMatchCount<0>=1
Project.unit<1>.triggerMatchCountWidth<0><0>=0
Project.unit<1>.triggerMatchType<0><0>=0
Project.unit<1>.triggerPortCount=1
Project.unit<1>.triggerPortIsData<0>=true
Project.unit<1>.triggerPortWidth<0>=188
Project.unit<1>.triggerSequencerLevels=16
Project.unit<1>.triggerSequencerType=1
Project.unit<1>.type=ilapro
